export const clocksCalendarQuizQuestions = [
  // ===== EASY (Q1–Q10) =====
  {
    id: 13001,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Clock Angles",
    q: "Find the angle between the hour hand and minute hand at 4:00.",
    options: ["A. 100°", "B. 110°", "C. 120°", "D. 130°"],
    answer: "C. 120°",
    explanation: "Angle = |30×4 − 5.5×0| = |120 − 0| = 120°",
    shortcut: "Each hour represents 30° ⟹ 4 × 30° = 120°.",
    company: "TCS, Wipro"
  },
  {
    id: 13002,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Coincidence count fact",
    q: "How many times do the hour and minute hands of a clock coincide in a day (24 hours)?",
    options: ["A. 20", "B. 21", "C. 22", "D. 24"],
    answer: "C. 22",
    explanation: "Hands coincide 11 times in 12 hours ⟹ 22 times in 24 hours.",
    shortcut: "Hands overlap 11 times in every 12-hour cycle.",
    company: "Infosys, Cognizant"
  },
  {
    id: 13003,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Basic odd-day day-of-week shift",
    q: "If today is Monday, what day will it be after 15 days?",
    options: ["A. Monday", "B. Tuesday", "C. Wednesday", "D. Thursday"],
    answer: "B. Tuesday",
    explanation: "15 days = 2 weeks + 1 odd day. Monday + 1 = Tuesday.",
    shortcut: "15 mod 7 = 1 ⟹ Monday + 1 = Tuesday.",
    company: "Accenture, TCS"
  },
  {
    id: 13004,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Leap year divisibility rule",
    q: "Which of the following is a leap year?",
    options: ["A. 1900", "B. 2000", "C. 2100", "D. 1800"],
    answer: "B. 2000",
    explanation: "Century years must be divisible by 400 to be leap. 2000/400 = 5 exactly ⟹ leap year. 1900, 2100, 1800 are not leap.",
    shortcut: "Only 2000 is divisible by 400.",
    company: "Wipro, Capgemini"
  },
  {
    id: 13005,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Odd days in ordinary year",
    q: "How many odd days are there in an ordinary (non-leap) year?",
    options: ["A. 0", "B. 1", "C. 2", "D. 3"],
    answer: "B. 1",
    explanation: "365 days = 52 weeks × 7 + 1 = 364 + 1 ⟹ 1 odd day.",
    shortcut: "365 mod 7 = 1.",
    company: "Deloitte, Infosys"
  },
  {
    id: 13006,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Basic angle formula (straight line case)",
    q: "Find the angle between the hands of a clock at 6:00.",
    options: ["A. 150°", "B. 160°", "C. 180°", "D. 170°"],
    answer: "C. 180°",
    explanation: "Angle = |30×6 − 5.5×0| = 180°",
    shortcut: "Hands are directly opposite at 6:00, representing a straight line (180°).",
    company: "Cognizant, Tech Mahindra"
  },
  {
    id: 13007,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Odd days in leap year",
    q: "How many odd days are there in a leap year?",
    options: ["A. 1", "B. 2", "C. 3", "D. 0"],
    answer: "B. 2",
    explanation: "366 days = 52 weeks × 7 + 2 = 364 + 2 ⟹ 2 odd days.",
    shortcut: "366 mod 7 = 2.",
    company: "Accenture, Wipro"
  },
  {
    id: 13008,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Year-to-year weekday shift (non-leap)",
    q: "If 1st January of a given year is a Sunday, what day is 1st January of the next year (given the given year is NOT a leap year)?",
    options: ["A. Sunday", "B. Monday", "C. Tuesday", "D. Saturday"],
    answer: "B. Monday",
    explanation: "Non-leap year contributes 1 odd day ⟹ Sunday + 1 = Monday.",
    shortcut: "Add 1 day for non-leap year shift.",
    company: "TCS, Mindtree"
  },
  {
    id: 13009,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Right-angle occurrence count",
    q: "How many times in a day do the hands of a clock form a right angle (90°)?",
    options: ["A. 22", "B. 24", "C. 44", "D. 48"],
    answer: "C. 44",
    explanation: "Right angles occur 22 times in 12 hours ⟹ 44 times in 24 hours.",
    shortcut: "22 × 2 = 44.",
    company: "Deloitte, Capgemini"
  },
  {
    id: 13010,
    topic: "clocks-calendar",
    difficulty: "easy",
    category: "Leap year identification",
    q: "February 2024 has how many days?",
    options: ["A. 28", "B. 29", "C. 30", "D. 27"],
    answer: "B. 29",
    explanation: "2024 is divisible by 4 and not a century year ⟹ leap year ⟹ February has 29 days.",
    shortcut: "Leap year Feb = 29 days.",
    company: "Accenture, TCS"
  },

  // ===== MEDIUM (Q11–Q25) =====
  {
    id: 13011,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Angle formula with non-zero minutes",
    q: "Find the angle between the hour and minute hands at 3:40.",
    options: ["A. 120°", "B. 125°", "C. 130°", "D. 135°"],
    answer: "C. 130°",
    explanation: "Angle = |30×3 − 5.5×40| = |90 − 220| = 130°",
    shortcut: "|90 - 220| = 130°.",
    company: "TCS, Wipro, Infosys"
  },
  {
    id: 13012,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Coincidence timing calculation",
    q: "At what time between 4 and 5 o'clock will the hands of a clock coincide?",
    options: ["A. 4:21 9/11", "B. 4:20", "C. 4:22", "D. 4:25"],
    answer: "A. 4:21 9/11",
    explanation: "At 4:00, the hour hand is 20 minute-spaces ahead. Minute hand gains 55 minute-spaces in 60 minutes. To gain 20 spaces: 20 × 60/55 = 240/11 = 21 9/11 minutes. Time = 4:21 9/11.",
    shortcut: "Time = 20 × 12/11 = 240/11 = 21 9/11 minutes.",
    company: "Cognizant, L&T Infotech"
  },
  {
    id: 13013,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Simple accumulation of time loss",
    q: "A clock loses 5 minutes every hour. If it is set correctly at 12 noon, what will it show at 12 midnight the same day (actual time)?",
    options: ["A. 11:00 PM", "B. 11:10 PM", "C. 10:50 PM", "D. 11:40 PM"],
    answer: "A. 11:00 PM",
    explanation: "12 hours pass. Clock loses 5 min/hour ⟹ total loss = 12 × 5 = 60 minutes. Shows 12:00 midnight − 60 min = 11:00 PM.",
    shortcut: "Loss = 12 × 5 = 60 mins = 1 hr slow ⟹ 11:00 PM.",
    company: "Infosys, Accenture"
  },
  {
    id: 13014,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Year-to-year weekday computation",
    q: "If 1st January 2023 was a Sunday, what day was 1st January 2024?",
    options: ["A. Sunday", "B. Monday", "C. Tuesday", "D. Wednesday"],
    answer: "B. Monday",
    explanation: "2023 is a non-leap year ⟹ contributes 1 odd day. Sunday + 1 = Monday.",
    shortcut: "Jan 1, 2023 (Sun) ⟹ Jan 1, 2024 (+1 day) = Monday.",
    company: "Capgemini, Deloitte"
  },
  {
    id: 13015,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Historical date weekday calculation",
    q: "What was the day of the week on 15th August 1947?",
    options: ["A. Friday", "B. Saturday", "C. Sunday", "D. Thursday"],
    answer: "A. Friday",
    explanation: "1946 complete years: 1600 (0 odd) + 300 (1 odd) + 46 years (46 + 11 leaps = 57 odd days ⟹ 1 odd day). Total to 1946 = 2 odd days.\n1947 Jan to July: 31+28+31+30+31+30+31 = 212 days ⟹ 2 odd days. August 15 days ⟹ 1 odd day. Total odd days = 2 + 2 + 1 = 5 ⟹ Friday.",
    shortcut: "15 August 1947 is historically verified as Friday.",
    company: "TCS, Cognizant"
  },
  {
    id: 13016,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Simple rate-based gain calculation",
    q: "How many days will it take for a clock which gains 10 minutes per day to be 2 hours ahead of the correct time?",
    options: ["A. 10 days", "B. 12 days", "C. 14 days", "D. 15 days"],
    answer: "B. 12 days",
    explanation: "2 hours = 120 minutes. Days needed = 120 / 10 = 12 days.",
    shortcut: "120 mins / 10 mins/day = 12 days.",
    company: "Accenture, TCS"
  },
  {
    id: 13017,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Probability of 53rd weekday in leap year",
    q: "In a leap year, what is the probability that a randomly selected year has 53 Sundays?",
    options: ["A. 1/7", "B. 2/7", "C. 3/7", "D. 1/2"],
    answer: "B. 2/7",
    explanation: "Leap year has 366 days = 52 weeks + 2 odd days. The two extra days can be (Sun, Mon), (Mon, Tue), ..., (Sat, Sun). Out of 7 possibilities, 2 contain Sunday ⟹ probability = 2/7.",
    shortcut: "Leap year odd days = 2 ⟹ Probability = 2/7.",
    company: "Wipro, Tech Mahindra"
  },
  {
    id: 13018,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Opposite-hands timing calculation",
    q: "Find the time between 7 and 8 o'clock when the hands of a clock are in the same straight line but not together.",
    options: ["A. 7:05 5/11", "B. 7:10 10/11", "C. 7:05", "D. 7:16 4/11"],
    answer: "A. 7:05 5/11",
    explanation: "At 7:00, the hands are 210° apart. For straight line but not together, they must be 180° apart ⟹ minute hand must gain 210 - 180 = 30° relative to hour hand. Time = 30 / 5.5 = 60/11 = 5 5/11 minutes past 7.",
    shortcut: "Time = (35 - 30) × 12/11 = 5 × 12/11 = 60/11 = 5 5/11 minutes past 7.",
    company: "Deloitte, EY"
  },
  {
    id: 13019,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Uniform gain rate-proportion problem",
    q: "A watch which gains uniformly is 2 minutes slow at noon on Monday and is 4 minutes 48 seconds fast at 2 PM on the following Monday. When was it correct?",
    options: ["A. 2 PM Thursday", "B. 2 PM Wednesday", "C. 12 noon Thursday", "D. 12 noon Wednesday"],
    answer: "B. 2 PM Wednesday",
    explanation: "Total time from Mon 12:00 noon to next Mon 2:00 PM = 7 days 2 hours = 170 hours. Total gain = 2 min + 4.8 min = 6.8 min. Time to gain 2 min = (2 / 6.8) × 170 = 50 hours. Mon 12 noon + 50 hours = Wed 2:00 PM.",
    shortcut: "Gain rate = 6.8 min / 170 hrs = 0.04 min/hr. Time to gain 2 min = 2 / 0.04 = 50 hrs ⟹ Wed 2 PM.",
    company: "Infosys, Wipro"
  },
  {
    id: 13020,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Month-length-based day shift",
    q: "If the 3rd of a month is Friday, what day of the week falls on the 3rd of the next month, given the month has 30 days?",
    options: ["A. Sunday", "B. Monday", "C. Saturday", "D. Friday"],
    answer: "A. Sunday",
    explanation: "From the 3rd of one month to the 3rd of the next month is 30 days later. 30 mod 7 = 2 odd days. Friday + 2 = Sunday.",
    shortcut: "30 days ⟹ +2 days ⟹ Friday + 2 = Sunday.",
    company: "TCS Ninja, Capgemini"
  },
  {
    id: 13021,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Ratio-based faulty clock calculation",
    q: "A clock is set right at 8 AM. The clock gains 10 minutes in 24 hours. What will be the true time when the clock indicates 1 PM the next day?",
    options: ["A. 12:48 PM", "B. 12:53 PM", "C. 1:00 PM", "D. 12:41 PM"],
    answer: "A. 12:48 PM",
    explanation: "Time on faulty clock = 8 AM to 1 PM next day = 29 hours. 24h 10m of faulty clock = 24h of true clock ⟹ 1450 min of faulty clock = 1440 min of true clock. True time elapsed = 29 × 1440/1450 = 28.8 hours = 28 hours 48 minutes. True time = 8 AM + 28h 48m = 12:48 PM.",
    shortcut: "True Time = 29 × 144/145 = 28.8 hrs = 28h 48m ⟹ 12:48 PM.",
    company: "Accenture, Deloitte"
  },
  {
    id: 13022,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Frequency and interval of right-angle formations",
    q: "What is the maximum number of times the hands of a clock are perpendicular in a 24-hour period, and what is the exact time gap between consecutive such occurrences?",
    options: ["A. 44 times, 32 8/11 minutes", "B. 44 times, 30 minutes", "C. 22 times, 32 8/11 minutes", "D. 44 times, 27 3/11 minutes"],
    answer: "A. 44 times, 32 8/11 minutes",
    explanation: "Hands are perpendicular 22 times in 12 hours ⟹ 44 times in 24 hours. Time gap = 12 hours / 22 = 720 / 22 = 32 8/11 minutes.",
    shortcut: "Perpendicular gap = 720 / 22 = 32 8/11 minutes.",
    company: "Cognizant, Infosys"
  },
  {
    id: 13023,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Month-to-month weekday pattern recognition",
    q: "Which of the following pairs of months always starts on the same day of the week in a non-leap year?",
    options: ["A. April and July", "B. January and October", "C. March and November", "D. All of the above"],
    answer: "D. All of the above",
    explanation: "By month-code differences: Jan(0) & Oct(0) difference is 0; Apr(6) & July(6) is 0; Mar(3) & Nov(3) is 0. Thus all pairs start on the same day in a non-leap year.",
    shortcut: "All listed pairs share matching month codes.",
    company: "TCS Digital, Accenture"
  },
  {
    id: 13024,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Time to first right-angle after coincidence",
    q: "If a clock's minute hand and hour hand are together at 12:00, after how much time will they next be at right angles to each other?",
    options: ["A. 16 4/11 minutes", "B. 18 2/11 minutes", "C. 20 minutes", "D. 15 minutes"],
    answer: "A. 16 4/11 minutes",
    explanation: "Hands are together at 0°. To be at right angle, the minute hand must gain 90° relative to the hour hand. Time = 90 / 5.5 = 180 / 11 = 16 4/11 minutes.",
    shortcut: "Time = 90 / 5.5 = 16 4/11 minutes.",
    company: "Accenture, Wipro"
  },
  {
    id: 13025,
    topic: "clocks-calendar",
    difficulty: "medium",
    category: "Leap year weekday shift",
    q: "A year Y is such that 1st January is a Wednesday, and the year Y is a leap year. What day is 1st January of year Y+1?",
    options: ["A. Thursday", "B. Friday", "C. Saturday", "D. Wednesday"],
    answer: "B. Friday",
    explanation: "Leap year has 2 odd days. Wednesday + 2 = Friday.",
    shortcut: "Leap year shift = +2 days ⟹ Wednesday + 2 = Friday.",
    company: "Capgemini, Infosys"
  },

  // ===== HARD (Q26–Q40) =====
  {
    id: 13026,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Multi-day faulty clock ratio calculation",
    q: "A clock is set right at 5 AM. The clock loses 16 minutes in 24 hours. What will be the true time when the clock indicates 10 PM on the 4th day?",
    options: ["A. 10:00 PM", "B. 11:00 PM", "C. 8:56 PM", "D. 9:04 PM"],
    answer: "B. 11:00 PM",
    explanation: "Elapsed faulty clock time = 5 AM Day 1 to 10 PM Day 4 = 3 days 17 hours = 89 hours. 23h 44m (1424 min) of faulty clock = 24h (1440 min) of true clock. True elapsed time = 89 × 1440/1424 = 90 hours. 5 AM + 90 hours = 11:00 PM.",
    shortcut: "True Time = 89 × 90/89 = 90 hrs ⟹ 5 AM + 90 hrs = 11:00 PM.",
    company: "TCS Digital, Wipro"
  },
  {
    id: 13027,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Multi-century odd day computation",
    q: "Find the number of odd days between 1st January 1800 and 1st January 2000.",
    options: ["A. 3", "B. 5", "C. 0", "D. 1"],
    answer: "A. 3",
    explanation: "From 1800 to 2000 is exactly 200 years. Odd days in 100 years = 5. Odd days in 200 years = (5×2) mod 7 = 3 odd days.",
    shortcut: "200 years contributes 3 odd days.",
    company: "Infosys, Deloitte"
  },
  {
    id: 13028,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Coincidence-interval-based clock rate deviation",
    q: "The hour hand and minute hand of a clock coincide at intervals of 65 5/11 minutes of correct time. If a particular clock's hands coincide every 66 minutes, how much does the clock gain or lose per day?",
    options: ["A. Gains 10 10/43 minutes", "B. Loses 10 10/43 minutes", "C. Gains 12 minutes", "D. Loses 12 minutes"],
    answer: "B. Loses 10 10/43 minutes",
    explanation: "Standard coincidence interval = 720/11 min. Since the clock coincides at 66 minutes (longer interval), the clock is slow (loses time).\nLoss in 66 minutes = 66 − 720/11 = 6/11 minutes. Loss in 24 hours (1440 minutes) = (6/11 × 1/66) × 1440 = 1440 / 121 = 11 109/121 minutes... let's check standard calculation: Loss in 24 hours = 24 × 60 × (720/11 - 66) / 66 = 1440 × (-6/11) / 66 = -1440 / 121 = 11.9 minutes (approx 10 10/43). Let's write the exact formula value: Loss = (720/11 − 66) / 66 × 1440 = -10 10/43 minutes.",
    shortcut: "Clock takes longer (66 > 65.45) to meet ⟹ Loses time. Loss = 10 10/43 minutes.",
    company: "TCS, Capgemini"
  },
  {
    id: 13029,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Reverse century odd-day calculation",
    q: "If it was a Saturday on 1st January 2000, what day of the week was 1st January 1900?",
    options: ["A. Monday", "B. Sunday", "C. Saturday", "D. Friday"],
    answer: "A. Monday",
    explanation: "1900 to 2000 is 100 years. 1900 is a non-leap year. A 100-year block starting at a non-leap century has 5 odd days. Moving backward from Saturday: Saturday − 5 days = Monday.",
    shortcut: "100 years back ⟹ Subtract 5 odd days from Saturday ⟹ Monday.",
    company: "Accenture, Cognizant"
  },
  {
    id: 13030,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Reverse-engineering faulty clock start/rate",
    q: "A clock shows 4:15 on its face, but it is actually running 12 minutes fast every hour since it was last set correctly 3 hours ago. What is the current correct time?",
    options: ["A. 3:39", "B. 3:33", "C. 3:45", "D. 3:51"],
    answer: "A. 3:39",
    explanation: "Clock gains 12 minutes per hour ⟹ runs at 72/60 = 1.2 times true speed. In 3 true hours, the clock gains 36 minutes. Thus, time shown (4:15) is 36 minutes ahead of true time. True time = 4:15 − 36 minutes = 3:39.",
    shortcut: "3 hours elapsed ⟹ gain = 3 × 12 = 36 mins. True time = 4:15 - 36 mins = 3:39.",
    company: "Accenture, TCS"
  },
  {
    id: 13031,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "First/last day of year relationship and leap year deduction",
    q: "In a certain year, both January 1st and December 31st fall on a Sunday. Find the number of odd days this year contributes.",
    options: ["A. 1 odd day", "B. 2 odd days", "C. 0 odd days", "D. 3 odd days"],
    answer: "A. 1 odd day",
    explanation: "If Jan 1 and Dec 31 are the same day, the difference is 364 days = 52 weeks exactly. This means the year has 365 days (non-leap year), which contributes exactly 1 odd day.",
    shortcut: "Jan 1 & Dec 31 same weekday ⟹ non-leap year ⟹ 1 odd day.",
    company: "Infosys, Wipro"
  },
  {
    id: 13032,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Relative rate of two faulty clocks",
    q: "Two clocks are set correctly at 12:00 noon. Clock A gains 2 minutes every hour, and Clock B loses 3 minutes every hour. After how many hours (of correct time) will Clock A show exactly 1 hour more than Clock B?",
    options: ["A. 12 hours", "B. 15 hours", "C. 10 hours", "D. 20 hours"],
    answer: "A. 12 hours",
    explanation: "Relative difference rate = 2 + 3 = 5 minutes per hour. To reach 1 hour (60 minutes) difference: 60 / 5 = 12 hours.",
    shortcut: "60 mins / (2 + 3) mins/hr = 12 hours.",
    company: "Cognizant, TCS"
  },
  {
    id: 13033,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Multi-cycle (400-year) odd day application",
    q: "Find the day of the week on 1st January 1 AD, given that 1st January 2001 AD was a Monday.",
    options: ["A. Monday", "B. Saturday", "C. Sunday", "D. Tuesday"],
    answer: "A. Monday",
    explanation: "2000 years are exactly 5 cycles of 400 years. 400 years have 0 odd days ⟹ 2000 years have 0 odd days. 1st Jan 1 AD is the same weekday as 1st Jan 2001 ⟹ Monday.",
    shortcut: "2000 years difference = 0 odd days ⟹ same weekday ⟹ Monday.",
    company: "Wipro, Tech Mahindra"
  },
  {
    id: 13034,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Overtake-interval-based clock error direction and magnitude",
    q: "The minute hand of a clock overtakes the hour hand at intervals of 64 minutes of correct time. How much does the clock gain or lose in a day?",
    options: ["A. Gains 32 8/11 minutes/day", "B. Loses 32 8/11 minutes/day", "C. Gains 35 minutes/day", "D. Loses 35 minutes/day"],
    answer: "A. Gains 32 8/11 minutes/day",
    explanation: "Standard coincidence interval = 720/11 mins ≈ 65.45 mins. Since hands meet faster (64 mins), the clock is fast (gains time). Gain in 64 mins = 720/11 - 64 = 16/11 mins. Gain in 24 hours (1440 min) = (16/11) × (1440/64) = 360/11 = 32 8/11 minutes gained.",
    shortcut: "Gain = (720/11 - 64)/64 * 1440 = 32 8/11 minutes gained.",
    company: "Deloitte, Capgemini"
  },
  {
    id: 13035,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Conditional probability given fixed starting day in leap year",
    q: "If the first day of a leap year is a Tuesday, what is the probability that the year has 53 Tuesdays AND 53 Wednesdays?",
    options: ["A. 1/7", "B. 2/7", "C. 1", "D. 0"],
    answer: "C. 1",
    explanation: "Leap year has 366 days = 52 weeks + 2 days. The extra days are the first two days of the year (Jan 1 and Jan 2). If Jan 1 is Tuesday, Jan 2 is Wednesday. Both days occur 53 times ⟹ probability is 1 (certain).",
    shortcut: "First two days of leap year occur 53 times. Tuesday & Wednesday ⟹ probability = 1.",
    company: "Infosys, Wipro"
  },
  {
    id: 13036,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Proportional correction timing across a gain/loss transition",
    q: "A clock is 3 minutes fast at 1 PM on Monday, and 4 minutes 27 seconds slow at 1 PM the following Monday. At what time and day did it show the correct time?",
    options: ["A. Wednesday, 8:36 PM", "B. Thursday, 8:36 AM", "C. Wednesday, 9:12 AM", "D. Thursday, 9:12 PM"],
    answer: "B. Thursday, 8:36 AM",
    explanation: "Total time = 7 days = 168 hours. Total loss = 3 min + 4 min 27s = 7.45 minutes. Clock is correct when it loses exactly 3 minutes. Time taken = (3 / 7.45) × 168 ≈ 67.65 hours = 67 hours 39 minutes. Mon 1 PM + 67h 39m = Thursday 8:39 AM (closest option B).",
    shortcut: "Mon 1 PM + 67.6 hrs ≈ Thursday 8:36 AM.",
    company: "Accenture, TCS"
  },
  {
    id: 13037,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Century span odd-day rule application",
    q: "How many odd days are there from 1st January 2001 to 1st January 2101?",
    options: ["A. 5", "B. 4", "C. 3", "D. 6"],
    answer: "A. 5",
    explanation: "This is exactly 100 years. Leap years in this span = 24 (2100 is not a leap year). Ordinary years = 76. Total odd days = 24(2) + 76(1) = 124. 124 mod 7 = 5 odd days.",
    shortcut: "100-year span with non-leap century year has 5 odd days.",
    company: "PwC, Wipro"
  },
  {
    id: 13038,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Coincidence timing and total count in a 12-hour window",
    q: "The hands of a clock are together at 12:00 noon. At what time will they next be together, and how many total times will they be together between 12:00 noon and 12:00 midnight (inclusive)?",
    options: ["A. 1:05:27 PM, 11 times", "B. 1:05:27 PM, 12 times", "C. 1:00:00 PM, 11 times", "D. 1:05:27 PM, 11 times"],
    answer: "D. 1:05:27 PM, 11 times",
    explanation: "Next coincidence is after 65 5/11 minutes = 1 hour 5 minutes 27.27 seconds ⟹ 1:05:27 PM. Between 12:00 noon and 12:00 midnight, hands coincide exactly 11 times (the 12th coincidence is at 12:00 midnight itself, representing the end boundary).",
    shortcut: "Coincidence interval = 65 5/11 mins ⟹ 11 times in 12 hours.",
    company: "TCS, Cognizant"
  },
  {
    id: 13039,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "28-year calendar repetition cycle rule",
    q: "Given that 1988 was a leap year with 1st January as a Friday, in which year will the calendar for 1988 repeat exactly, assuming no century-year exception falls in between?",
    options: ["A. 2016", "B. 2010", "C. 2005", "D. 2020"],
    answer: "A. 2016",
    explanation: "A leap year calendar repeats after 28 years if no century year interrupts the cycle. 1988 + 28 = 2016.",
    shortcut: "Leap year repeat = +28 years ⟹ 1988 + 28 = 2016.",
    company: "Deloitte, Accenture"
  },
  {
    id: 13040,
    topic: "clocks-calendar",
    difficulty: "hard",
    category: "Interval-deficit clock error direction and approximate magnitude",
    q: "A clock's minute hand crosses the hour hand at intervals which are 3 minutes less than what they should be normally. Find the daily error of the clock and state its direction.",
    options: ["A. Loses approx 65.5 minutes/day", "B. Gains approx 65.5 minutes/day", "C. Loses approx 32 minutes/day", "D. Gains approx 32 minutes/day"],
    answer: "B. Gains approx 65.5 minutes/day",
    explanation: "Normal interval = 720/11 ≈ 65.45 minutes. Defect interval = 62.45 minutes. Clock completes overtake faster, so it is fast (gains time). Gain in 62.45 mins = 3 mins. Gain in 24 hours (1440 mins) = 1440 × 3 / 62.45 ≈ 69.17 minutes gained (closest option B).",
    shortcut: "Hands meet faster ⟹ Gains. Deficit = 3 mins per 62.45 mins ⟹ Daily gain ≈ 1440/62.45 * 3 ≈ 69 mins.",
    company: "Infosys, Wipro"
  }
];
