export const permutationCombinationQuizQuestions = [
  // ===== EASY (Q1–Q10) =====
  {
    id: 17001,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Basic permutation formula",
    q: "Evaluate ⁵P₃.",
    options: ["A. 60", "B. 50", "C. 40", "D. 30"],
    answer: "A. 60",
    explanation: "⁵P₃ = 5! / (5 − 3)! = 5! / 2! = (5×4×3×2×1) / (2×1) = 60.",
    shortcut: "5 × 4 × 3 = 60.",
    company: "TCS, Wipro"
  },
  {
    id: 17002,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Basic combination formula",
    q: "Evaluate ⁶C₂.",
    options: ["A. 12", "B. 15", "C. 18", "D. 20"],
    answer: "B. 15",
    explanation: "⁶C₂ = 6! / (2! × 4!) = (6 × 5) / (2 × 1) = 15.",
    shortcut: "(6 × 5) / 2 = 15.",
    company: "Infosys, Cognizant"
  },
  {
    id: 17003,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Basic linear arrangement",
    q: "In how many ways can 5 different books be arranged on a shelf?",
    options: ["A. 100", "B. 120", "C. 60", "D. 24"],
    answer: "B. 120",
    explanation: "5 distinct items arranged in a row = 5! = 120.",
    shortcut: "5! = 120.",
    company: "Accenture, TCS"
  },
  {
    id: 17004,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Basic combination committee selection",
    q: "How many ways can a committee of 3 be selected from 8 people?",
    options: ["A. 56", "B. 48", "C. 64", "D. 40"],
    answer: "A. 56",
    explanation: "⁸C₃ = 8! / (3! × 5!) = (8 × 7 × 6) / (3 × 2 × 1) = 56.",
    shortcut: "(8 × 7 × 6) / 6 = 56.",
    company: "Wipro, Capgemini"
  },
  {
    id: 17005,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Permutation digit-based numbers",
    q: "How many 3-digit numbers can be formed using digits 1, 2, 3, 4, 5 without repetition?",
    options: ["A. 60", "B. 50", "C. 40", "D. 45"],
    answer: "A. 60",
    explanation: "⁵P₃ = 5 × 4 × 3 = 60.",
    shortcut: "5 × 4 × 3 = 60.",
    company: "Deloitte, Infosys"
  },
  {
    id: 17006,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Basic circular permutation",
    q: "In how many ways can 4 people be seated in a circle?",
    options: ["A. 24", "B. 12", "C. 6", "D. 4"],
    answer: "C. 6",
    explanation: "Circular permutation of n objects = (n − 1)! = (4 − 1)! = 3! = 6.",
    shortcut: "(4 − 1)! = 6.",
    company: "Cognizant, Tech Mahindra"
  },
  {
    id: 17007,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Basic word arrangement distinct letters",
    q: "How many ways can the letters of the word 'CAT' be arranged?",
    options: ["A. 3", "B. 6", "C. 9", "D. 12"],
    answer: "B. 6",
    explanation: "3 distinct letters ⟹ 3! = 6.",
    shortcut: "3! = 6.",
    company: "Accenture, Wipro"
  },
  {
    id: 17008,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Permutation repeated letters",
    q: "How many ways can the letters of the word 'APPLE' be arranged (letters: A,P,P,L,E)?",
    options: ["A. 60", "B. 120", "C. 20", "D. 30"],
    answer: "A. 60",
    explanation: "Total letters = 5, with P repeated twice. Arrangements = 5! / 2! = 120 / 2 = 60.",
    shortcut: "120 / 2 = 60.",
    company: "TCS, Mindtree"
  },
  {
    id: 17009,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Repetition-allowed counting",
    q: "In how many ways can a coin be tossed 3 times, noting the sequence of heads/tails?",
    options: ["A. 6", "B. 8", "C. 9", "D. 12"],
    answer: "B. 8",
    explanation: "Each toss has 2 outcomes. 3 tosses ⟹ 2³ = 8.",
    shortcut: "2³ = 8.",
    company: "Deloitte, Capgemini"
  },
  {
    id: 17010,
    topic: "permutation-combination",
    difficulty: "easy",
    category: "Combination diagonal counting",
    q: "How many diagonals does a hexagon (6 sides) have?",
    options: ["A. 6", "B. 9", "C. 12", "D. 15"],
    answer: "B. 9",
    explanation: "Total line segments between 6 vertices = ⁶C₂ = 15. Subtract the 6 sides (which are not diagonals) ⟹ 15 − 6 = 9 diagonals.",
    shortcut: "⁶C₂ − 6 = 15 − 6 = 9.",
    company: "Accenture, TCS"
  },

  // ===== MEDIUM (Q11–Q25) =====
  {
    id: 17011,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Selection and arrangement",
    q: "A word is to be formed using 4 consonants and 3 vowels selected from 9 consonants and 5 vowels. How many such words can be formed?",
    options: ["A. 6350400", "B. 6250400", "C. 6450500", "D. 6150300"],
    answer: "A. 6350400",
    explanation: "Choose 4 consonants from 9: ⁹C₄ = 126. Choose 3 vowels from 5: ⁵C₃ = 10. Combined selections = 126 × 10 = 1260. Arrange 7 selected letters: 7! = 5040. Total words = 1260 × 5040 = 6,350,400.",
    shortcut: "⁹C₄ × ⁵C₃ × 7! = 126 × 10 × 5040 = 6,350,400.",
    company: "TCS, Wipro, Infosys"
  },
  {
    id: 17012,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Selection identical items at least one",
    q: "A fruit basket has 4 bananas, 7 apples, and 6 mangoes (identical within each type). In how many ways can a person select at least one fruit?",
    options: ["A. 279", "B. 280", "C. 250", "D. 300"],
    answer: "A. 279",
    explanation: "Ways to select bananas = 5 (0 to 4). Apples = 8 (0 to 7). Mangoes = 7 (0 to 6). Total ways including none = 5 × 8 × 7 = 280. Subtract the 'select none' case: 280 − 1 = 279.",
    shortcut: "(4+1)(7+1)(6+1) − 1 = 279.",
    company: "Cognizant, L&T Infotech"
  },
  {
    id: 17013,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Restricted position permutation",
    q: "Find the number of arrangements of the word 'RAINBOW' (7 distinct letters) such that the 3 vowels (A, I, O) occupy only even positions.",
    options: ["A. 144", "B. 188", "C. 222", "D. 234"],
    answer: "A. 144",
    explanation: "Even positions in a 7-letter word are 2, 4, and 6. Vowels (3 of them) arranged in these 3 positions: 3! = 6 ways. Remaining 4 consonants arranged in the remaining 4 positions: 4! = 24 ways. Total = 6 × 24 = 144.",
    shortcut: "3! × 4! = 6 × 24 = 144.",
    company: "Infosys, Accenture"
  },
  {
    id: 17014,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Repetition-allowed attempts count",
    q: "A password lock has 5 rings, each with 7 different symbols. Find the maximum number of unsuccessful attempts before the correct password must be found.",
    options: ["A. 16806", "B. 16807", "C. 18625", "D. 15555"],
    answer: "A. 16806",
    explanation: "Total possible combinations = 7⁵ = 16,807. Only one combination is correct ⟹ maximum unsuccessful attempts = 16,807 − 1 = 16,806.",
    shortcut: "7⁵ − 1 = 16,806.",
    company: "Capgemini, Deloitte"
  },
  {
    id: 17015,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Permutation without repetition",
    q: "Using digits 1, 3, 4, 5, 6, 7, 8 (no repetition), how many 5-digit numbers can be formed?",
    options: ["A. 2520", "B. 2400", "C. 2300", "D. 2500"],
    answer: "A. 2520",
    explanation: "Permutation of 7 digits taken 5 at a time = ⁷P₅ = 7 × 6 × 5 × 4 × 3 = 2520.",
    shortcut: "⁷P₅ = 2520.",
    company: "TCS, Cognizant"
  },
  {
    id: 17016,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Restricted even number formation",
    q: "Using digits 1, 2, 3, 5, 7, 9 (no repetition), how many 4-digit EVEN numbers can be formed?",
    options: ["A. 60", "B. 70", "C. 80", "D. 90"],
    answer: "A. 60",
    explanation: "For an even number, the units place must be 2 (1 choice). The remaining 3 positions are filled from the remaining 5 digits: ⁵P₃ = 5 × 4 × 3 = 60.",
    shortcut: "⁵P₃ × 1 = 60.",
    company: "Accenture, TCS"
  },
  {
    id: 17017,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Fixed relative order block method",
    q: "A, B, C, D along with 6 other people must stand in a queue such that A is always before B, B before C, and C before D. Find the number of such arrangements.",
    options: ["A. 151200", "B. 3628800", "C. 725760", "D. 120960"],
    answer: "A. 151200",
    explanation: "Total arrangements of 10 people = 10! = 3,628,800. Since A, B, C, D must appear in a single fixed relative order (A < B < C < D), we divide by the number of their internal arrangements: 10! / 4! = 3,628,800 / 24 = 151,200.",
    shortcut: "10! / 24 = 151,200.",
    company: "Wipro, Tech Mahindra"
  },
  {
    id: 17018,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Triangle counting from line points",
    q: "There are 10 points on line AB and 8 points on line AC (excluding point A). How many triangles can be formed using these points?",
    options: ["A. 640", "B. 600", "C. 700", "D. 800"],
    answer: "A. 640",
    explanation: "Case 1: 2 points from AB, 1 from AC = ¹⁰C₂ × ⁸C₁ = 45 × 8 = 360. Case 2: 2 points from AC, 1 from AB = ⁸C₂ × ¹⁰C₁ = 28 × 10 = 280. Total triangles = 360 + 280 = 640.",
    shortcut: "45×8 + 28×10 = 640.",
    company: "Deloitte, EY"
  },
  {
    id: 17019,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Diophantine equation solution count",
    q: "Find the number of ways a batsman can score exactly 200 runs using only 4s and 6s (order doesn't matter, at least one of each is used).",
    options: ["A. 16", "B. 17", "C. 18", "D. 15"],
    answer: "A. 16",
    explanation: "Let x be the number of 4s and y be 6s. 4x + 6y = 200 ⟹ 2x + 3y = 100 ⟹ x = (100 − 3y)/2. For x to be a positive integer, y must be even and positive. Thus y can take values 2, 4, ..., 32. This gives (32 − 2)/2 + 1 = 16 solutions.",
    shortcut: "y values: 2, 4, ..., 32 ⟹ 16 solutions.",
    company: "Infosys, Wipro"
  },
  {
    id: 17020,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Bounded digit formation",
    q: "How many positive integers not exceeding 4300 can be formed using digits 0, 1, 2, 3, 4 (repetition allowed)?",
    options: ["A. 675", "B. 575", "C. 750", "D. 800"],
    answer: "B. 575",
    explanation: "1-digit: 4. 2-digit: 4×5 = 20. 3-digit: 4×5×5 = 100. 4-digit starting with 1,2,3: 3×5³ = 375. 4-digit starting with 4 (less than 4300 ⟹ 2nd digit is 0,1,2): 1×3×5² = 75. Number 4300 itself: 1. Total = 4 + 20 + 100 + 375 + 75 + 1 = 575.",
    shortcut: "Sum = 4 + 20 + 100 + 375 + 75 + 1 = 575.",
    company: "TCS Ninja, Capgemini"
  },
  {
    id: 17021,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "At most k constraint",
    q: "A team of 11 is to be selected from 5 men and 11 women such that the team has at most 3 men. Find the number of ways.",
    options: ["A. 2256", "B. 2226", "C. 2235", "D. 2000"],
    answer: "A. 2256",
    explanation: "Sum combinations for 0, 1, 2, 3 men: 0 men: ⁵C₀ × ¹¹C₁₁ = 1. 1 man: ⁵C₁ × ¹¹C₁₀ = 5 × 11 = 55. 2 men: ⁵C₂ × ¹¹C₉ = 10 × 55 = 550. 3 men: ⁵C₃ × ¹¹C₈ = 10 × 165 = 1650. Total = 1 + 55 + 550 + 1650 = 2256.",
    shortcut: "1 + 55 + 550 + 1650 = 2256.",
    company: "Accenture, Deloitte"
  },
  {
    id: 17022,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Probability with replacement",
    q: "From a bag with 8 green and 5 red balls, 3 balls are drawn one after another WITH replacement. Find the probability that all 3 are green.",
    options: ["A. 512/2197", "B. 502/2197", "C. 512/3197", "D. 513/2197"],
    answer: "A. 512/2197",
    explanation: "P(green in single draw) = 8 / 13. With replacement ⟹ draws are independent. P(all 3 green) = (8 / 13)³ = 512 / 2197.",
    shortcut: "(8/13)³ = 512 / 2197.",
    company: "Cognizant, Infosys"
  },
  {
    id: 17023,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Probability without replacement",
    q: "From a bag with 8 green and 5 red balls, 3 balls are drawn one after another WITHOUT replacement. Find the probability that all 3 are green.",
    options: ["A. 336/1716", "B. 236/1716", "C. 336/1816", "D. 346/1716"],
    answer: "A. 336/1716",
    explanation: "Probability = (8/13) × (7/12) × (6/11) = 336 / 1716.",
    shortcut: "(8×7×6) / (13×12×11) = 336 / 1716.",
    company: "TCS Digital, Accenture"
  },
  {
    id: 17024,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Total probability multiple bags",
    q: "Bag 1 has 8 white, 3 blue balls; Bag 2 has 7 white, 4 blue balls. A bag is chosen at random, then a ball is drawn. Find the probability of drawing a blue ball.",
    options: ["A. 6/22", "B. 7/22", "C. 8/22", "D. 9/22"],
    answer: "B. 7/22",
    explanation: "P(Bag 1) = 1/2, P(Blue | Bag 1) = 3/11. P(Bag 2) = 1/2, P(Blue | Bag 2) = 4/11. Total Probability = (1/2)(3/11) + (1/2)(4/11) = 7/22.",
    shortcut: "(3/22) + (4/22) = 7/22.",
    company: "Accenture, Wipro"
  },
  {
    id: 17025,
    topic: "permutation-combination",
    difficulty: "medium",
    category: "Combination sample space",
    q: "Two chips are drawn from a box containing 3 white, 7 blue, and 16 green chips. Find the total number of ways to choose 2 chips.",
    options: ["A. 325", "B. 300", "C. 350", "D. 275"],
    answer: "A. 325",
    explanation: "Total chips = 3 + 7 + 16 = 26. Ways to choose 2 chips = ²⁶C₂ = 26 × 25 / 2 = 325.",
    shortcut: "²⁶C₂ = 325.",
    company: "Capgemini, Infosys"
  },

  // ===== HARD (Q26–Q40) =====
  {
    id: 17026,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Dictionary-order rank of word",
    q: "The letters of the word 'ROADIE' are permuted and arranged in alphabetical order. Find the word at the 44th rank.",
    options: ["A. AERDOA", "B. AERDOI", "C. ADRDOI", "D. BERDOI"],
    answer: "B. AERDOI",
    explanation: "Letters: A, D, E, I, O, R. Words starting with A: 5! = 120. Ranks < 44 start with A. Second letter: 'AD___' ⟹ 4! = 24. Remaining rank = 44 − 24 = 20 within 'AE___'. 'AED___' ⟹ 3! = 6. 'AEI___' ⟹ 3! = 6. 'AEO___' ⟹ 3! = 6. Total so far = 18. The 20th rank falls in 'AER___' (specifically the 2nd alphabetical word: AERDIO is 1st, AERDOI is 2nd).",
    shortcut: "AD (24) ⟹ AE (next 20). AED (6), AEI (6), AEO (6) ⟹ Rank 44 is 2nd word of AER ⟹ AERDOI.",
    company: "TCS Digital, Wipro"
  },
  {
    id: 17027,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Jealous couples river crossing",
    q: "4 married couples cross a river in a 2-person boat. No wife can cross with any man other than her husband, and no husband with any woman other than his wife. Find the minimum crossings.",
    options: ["A. 19", "B. 14", "C. 11", "D. 16"],
    answer: "D. 16",
    explanation: "Using the established constraint-satisfaction crossing sequence: each additional couple requires 4 one-way crossings. For 4 couples, the minimum number of one-way crossings is 16.",
    shortcut: "4 couples × 4 crossings = 16.",
    company: "Infosys, Deloitte"
  },
  {
    id: 17028,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "CRT system solving",
    q: "A person remembers numbers by their remainders when divided by 3, 5, and 7. He has (1,1,6) rupees and pays (2,0,6) rupees to a servant. How much money is left?",
    options: ["A. 50", "B. 56", "C. 60", "D. 80"],
    answer: "B. 56",
    explanation: "For (1,1,6): N mod 3=1, N mod 5=1, N mod 7=6. Checking values shows N = 76. For (2,0,6): N mod 3=2, N mod 5=0, N mod 7=6. Checking values shows N = 20. Money left = 76 − 20 = 56.",
    shortcut: "76 − 20 = 56.",
    company: "TCS, Capgemini"
  },
  {
    id: 17029,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Fractional algebraic equations",
    q: "2/3rd of the balls are blue, rest are pink. 5/9th of blue and 7/8th of pink are defective. If non-defective balls are 146, find the total balls.",
    options: ["A. 432", "B. 500", "C. 700", "D. 800"],
    answer: "A. 432",
    explanation: "Let total = x. Blue = 2x/3, Pink = x/3. Defective blue = 10x/27, defective pink = 7x/24. Total defective = (80x + 63x)/216 = 143x/216. Non-defective = 73x/216 = 146 ⟹ x = 146 × 216 / 73 = 432.",
    shortcut: "73x / 216 = 146 ⟹ x = 432.",
    company: "Accenture, Cognizant"
  },
  {
    id: 17030,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Set overlap committee member count",
    q: "Three committees X, Y, Z share 2 members in common to all. Every pair of committees shares exactly 3 members. Find the minimum possible members on any one committee.",
    options: ["A. 3", "B. 4", "C. 5", "D. 6"],
    answer: "B. 4",
    explanation: "X ∩ Y ∩ Z = 2. Since any pair shares exactly 3, there is 3 − 2 = 1 unique member shared per pair. X = {all-shared (2) + shared-with-Y (1) + shared-with-Z (1)} = 4. Similarly for Y and Z. Min members = 4.",
    shortcut: "Min size = 2 + 1 + 1 = 4.",
    company: "Accenture, TCS"
  },
  {
    id: 17031,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Simultaneous linear equations",
    q: "3 mangoes and 4 apples cost Rs. 85. 5 apples and 6 peaches cost Rs. 122. 6 mangoes and 2 peaches cost Rs. 114. Find the sum of cost of 1 apple, 1 peach, and 1 mango.",
    options: ["A. 37", "B. 38", "C. 39", "D. 40"],
    answer: "A. 37",
    explanation: "3m + 4a = 85 (i); 5a + 6p = 122 (ii); 6m + 2p = 114 (iii). Multiply (i) by 2: 6m + 8a = 170. Subtract (iii): 8a − 2p = 56 ⟹ p = 4a − 28. Substitute in (ii): 5a + 6(4a − 28) = 122 ⟹ 29a = 290 ⟹ a = 10. Then p = 12, m = 15. Sum = 10 + 12 + 15 = 37.",
    shortcut: "Solve for a=10, p=12, m=15 ⟹ 10 + 12 + 15 = 37.",
    company: "Infosys, Wipro"
  },
  {
    id: 17032,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Circular arrangement beads reflective",
    q: "In how many ways can 6 distinct beads be arranged to form a necklace?",
    options: ["A. 120", "B. 60", "C. 720", "D. 360"],
    answer: "B. 60",
    explanation: "Circular permutation of 6 distinct beads = (6 − 1)! = 120. In a necklace, clockwise and anticlockwise are reflective-identical ⟹ 120 / 2 = 60.",
    shortcut: "(n−1)! / 2 = 120 / 2 = 60.",
    company: "Cognizant, TCS"
  },
  {
    id: 17033,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Division into equal unlabelled groups",
    q: "How many ways can 12 different books be divided equally into 3 unlabelled groups of 4 books each?",
    options: ["A. 34,650", "B. 5,775", "C. 17,325", "D. 11,550"],
    answer: "B. 5,775",
    explanation: "Ways to divide into labelled groups: ¹²C₄ × ⁸C₄ × ⁴C₄ = 495 × 70 × 1 = 34,650. Since groups are unlabelled, divide by 3! ⟹ 34,650 / 6 = 5775.",
    shortcut: "(¹²C₄ × ⁸C₄) / 3! = 34650 / 6 = 5775.",
    company: "Wipro, Tech Mahindra"
  },
  {
    id: 17034,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "At least constraint committee selection",
    q: "A committee of 5 is to be formed from 6 men and 4 women, such that the committee has at least 2 women. Find the number of ways.",
    options: ["A. 186", "B. 246", "C. 210", "D. 196"],
    answer: "A. 186",
    explanation: "Case 1: 2W, 3M ⟹ ⁴C₂ × ⁶C₃ = 6 × 20 = 120. Case 2: 3W, 2M ⟹ ⁴C₃ × ⁶C₂ = 4 × 15 = 60. Case 3: 4W, 1M ⟹ ⁴C₄ × ⁶C₁ = 1 × 6 = 6. Total = 120 + 60 + 6 = 186.",
    shortcut: "120 + 60 + 6 = 186.",
    company: "Deloitte, Capgemini"
  },
  {
    id: 17035,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Permutation with multiple repeated letters",
    q: "Find the number of ways to arrange the letters of the word 'MISSISSIPPI'.",
    options: ["A. 34,650", "B. 39,916,800", "C. 11,880", "D. 17,325"],
    answer: "A. 34,650",
    explanation: "Total letters = 11. Repeated letters: I (4 times), S (4 times), P (2 times). Arrangements = 11! / (4! × 4! × 2!) = 39,916,800 / 1152 = 34,650.",
    shortcut: "11! / (24 × 24 × 2) = 34,650.",
    company: "Infosys, Wipro"
  },
  {
    id: 17036,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Distribution distinct items onto functions",
    q: "In how many ways can 5 different colored balls be distributed into 3 distinct boxes such that no box is empty?",
    options: ["A. 150", "B. 180", "C. 120", "D. 210"],
    answer: "A. 150",
    explanation: "Using inclusion-exclusion: Total distributions = 3⁵ = 243. Subtract invalid cases: ³C₁ × 2⁵ = 96. Add back overlap: ³C₂ × 1⁵ = 3. Total ways = 243 − 96 + 3 = 150.",
    shortcut: "3⁵ − 3×2⁵ + 3×1⁵ = 150.",
    company: "Accenture, TCS"
  },
  {
    id: 17037,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "At most constraint committee selection",
    q: "Find the number of ways to select a committee of 4 from 7 men and 6 women such that the committee has at most 2 men.",
    options: ["A. 470", "B. 590", "C. 620", "D. 600"],
    answer: "A. 470",
    explanation: "Case 1: 0 men, 4 women ⟹ ⁷C₀ × ⁶C₄ = 1 × 15 = 15. Case 2: 1 man, 3 women ⟹ ⁷C₁ × ⁶C₃ = 7 × 20 = 140. Case 3: 2 men, 2 women ⟹ ⁷C₂ × ⁶C₂ = 21 × 15 = 315. Total = 15 + 140 + 315 = 470.",
    shortcut: "15 + 140 + 315 = 470.",
    company: "PwC, Wipro"
  },
  {
    id: 17038,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Leading digit constraint permutation",
    q: "How many 4-digit numbers greater than 5000 can be formed using digits 2, 3, 5, 6, 8 without repetition?",
    options: ["A. 72", "B. 60", "C. 84", "D. 96"],
    answer: "A. 72",
    explanation: "For the number to be > 5000, the first digit must be 5, 6, or 8 (3 choices). The remaining 3 positions are filled using 4 remaining digits: ⁴P₃ = 4 × 3 × 2 = 24. Total = 3 × 24 = 72.",
    shortcut: "3 × 24 = 72.",
    company: "TCS, Cognizant"
  },
  {
    id: 17039,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Diagonal formula reverse application",
    q: "A polygon has 44 diagonals. Find the number of sides of the polygon.",
    options: ["A. 11", "B. 10", "C. 12", "D. 9"],
    answer: "A. 11",
    explanation: "Number of diagonals = n(n − 3) / 2 = 44 ⟹ n(n − 3) = 88 ⟹ n² − 3n − 88 = 0 ⟹ (n − 11)(n + 8) = 0 ⟹ n = 11.",
    shortcut: "11 × 8 / 2 = 44 ⟹ n = 11.",
    company: "Deloitte, Accenture"
  },
  {
    id: 17040,
    topic: "permutation-combination",
    difficulty: "hard",
    category: "Vowels together block permutation",
    q: "In how many ways can the letters of the word 'EQUATION' be arranged such that all vowels occur together?",
    options: ["A. 720×120", "B. 4! × 5!", "C. 4! × 5! = 2880", "D. Both B and C"],
    answer: "D. Both B and C",
    explanation: "Vowels: E, U, A, I, O (5 vowels). Consonants: Q, T, N (3 consonants). Treat 5 vowels as a single block. 1 block + 3 consonants = 4 units. Arrange 4 units: 4! = 24. Arrange 5 vowels inside the block: 5! = 120. Total = 4! × 5! = 2880.",
    shortcut: "4! × 5! = 2880.",
    company: "Infosys, Wipro"
  }
];
