export const probabilityQuizQuestions = [
  // === EASY (Q1-Q10) ===
  {
    id: 6001,
    topic: "probability",
    difficulty: "easy",
    category: "Cubes",
    q: "A book contains 100 pages. Sohail randomly selects a page. What is the probability that the page number is a cube number?",
    options: ["A) 0.04", "B) 0.20", "C) 0.02", "D) 0.4"],
    answer: "A) 0.04",
    explanation: "Cube numbers from 1 to 100 are: 1³=1, 2³=8, 3³=27, and 4³=64 (4 numbers total).\nProbability P(E) = Favorable outcomes / Total outcomes = 4 / 100 = 0.04.",
    shortcut: "Identify perfect cubes up to 100: 1, 8, 27, 64. Count = 4. 4/100 = 0.04.",
    company: "TCS, Wipro"
  },
  {
    id: 6002,
    topic: "probability",
    difficulty: "easy",
    category: "Multiples",
    q: "Tickets numbered 1 to 20 are mixed up and then a ticket is drawn at random. What is the probability that the ticket drawn has a number which is a multiple of 3 or 5?",
    options: ["A) 1/2", "B) 2/5", "C) 9/20", "D) 1/4"],
    answer: "C) 9/20",
    explanation: "Sample space S = {1, 2, ..., 20} (n(S) = 20).\nMultiples of 3 = {3, 6, 9, 12, 15, 18} (6 numbers).\nMultiples of 5 = {5, 10, 15, 20} (4 numbers).\nMultiples of 3 or 5 = {3, 5, 6, 9, 10, 12, 15, 18, 20} (9 distinct numbers after removing double-counted 15).\nProbability P(E) = 9/20.",
    shortcut: "Multiples count = 6 (of 3) + 4 (of 5) - 1 (common multiple 15) = 9. P = 9/20.",
    company: "Infosys, Cognizant"
  },
  {
    id: 6003,
    topic: "probability",
    difficulty: "easy",
    category: "Cards",
    q: "A card is drawn from a pack of 52 cards. The probability of getting a queen of club or a king of heart is?",
    options: ["A) 1/13", "B) 2/13", "C) 1/26", "D) 1/52"],
    answer: "C) 1/26",
    explanation: "Total cards = 52.\nFavorable cards: Queen of clubs (1 card) or King of hearts (1 card) = 2 cards total.\nProbability P(E) = 2 / 52 = 1 / 26.",
    shortcut: "Mutually exclusive single cards: 1/52 + 1/52 = 2/52 = 1/26.",
    company: "Accenture"
  },
  {
    id: 6004,
    topic: "probability",
    difficulty: "easy",
    category: "Cards",
    q: "One card is drawn at random from a pack of 52 cards. What is the probability that the card drawn is a face card (Jack, Queen, and King only)?",
    options: ["A) 1/13", "B) 3/13", "C) 1/4", "D) 9/52"],
    answer: "B) 3/13",
    explanation: "Total face cards in a deck = 4 suits * 3 face cards (J, Q, K) = 12 cards.\nProbability P = 12 / 52 = 3 / 13.",
    shortcut: "Each suit has 3 face cards out of 13. P = 3/13.",
    company: "TCS Ninja"
  },
  {
    id: 6005,
    topic: "probability",
    difficulty: "easy",
    category: "Ball Drawings",
    q: "A bag contains 6 black balls and 8 white balls. One ball is drawn at random from the bag. What is the probability that it is a white ball?",
    options: ["A) 3/4", "B) 4/7", "C) 1/8", "D) 3/7"],
    answer: "B) 4/7",
    explanation: "Total number of balls = 6 + 8 = 14.\nFavorable (white) balls = 8.\nProbability P = 8 / 14 = 4 / 7.",
    shortcut: "White/Total = 8/14 = 4/7.",
    company: "Wipro"
  },
  {
    id: 6006,
    topic: "probability",
    difficulty: "easy",
    category: "Bulbs",
    q: "A box contains 15 electric bulbs, out of which 6 are defective. One bulb is drawn at random. What is the probability that the drawn bulb is defective?",
    options: ["A) 1/5", "B) 1/3", "C) 2/5", "D) 4/15"],
    answer: "C) 2/5",
    explanation: "Total bulbs = 15. Defective bulbs = 6.\nProbability P = Defective / Total = 6 / 15 = 2 / 5.",
    shortcut: "6/15 = 2/5.",
    company: "Capgemini"
  },
  {
    id: 6007,
    topic: "probability",
    difficulty: "easy",
    category: "Complementary Events",
    q: "A bag comprises eight white balls and twelve blue balls. If a ball is chosen randomly from the bag, find the probability of receiving a blue ball, and of receiving no blue ball.",
    options: ["A) 6/5 & 2/5", "B) 5/9 & 3/5", "C) 10/11 & 2/3", "D) 3/5 & 2/5"],
    answer: "D) 3/5 & 2/5",
    explanation: "Total balls = 8 + 12 = 20.\nProbability of blue ball = 12 / 20 = 3/5.\nProbability of no blue ball = 1 - P(blue) = 1 - 3/5 = 2/5.",
    shortcut: "Blue ratio = 12/20 = 3/5. Complement = 1 - 3/5 = 2/5.",
    company: "Infosys"
  },
  {
    id: 6008,
    topic: "probability",
    difficulty: "easy",
    category: "Dice",
    q: "A single die is thrown once. What is the probability of getting an even number?",
    options: ["A) 1/6", "B) 1/3", "C) 1/2", "D) 2/3"],
    answer: "C) 1/2",
    explanation: "Total outcomes = {1, 2, 3, 4, 5, 6} (6 outcomes).\nEven numbers = {2, 4, 6} (3 outcomes).\nProbability P = 3 / 6 = 1 / 2.",
    shortcut: "Half the numbers on a die are even => 1/2.",
    company: "Cognizant"
  },
  {
    id: 6009,
    topic: "probability",
    difficulty: "easy",
    category: "Ball Drawings",
    q: "A bag contains 4 red and 6 green balls. One ball is drawn at random. Find the probability that it is red.",
    options: ["A) 1/5", "B) 2/5", "C) 3/5", "D) 4/5"],
    answer: "B) 2/5",
    explanation: "Total balls = 4 + 6 = 10.\nRed balls = 4.\nProbability P = 4 / 10 = 2 / 5.",
    shortcut: "Red/Total = 4/10 = 2/5.",
    company: "Accenture"
  },
  {
    id: 6010,
    topic: "probability",
    difficulty: "easy",
    category: "Dice",
    q: "What is the probability of getting a number greater than 4 when a die is rolled once?",
    options: ["A) 1/6", "B) 1/3", "C) 1/2", "D) 2/3"],
    answer: "B) 1/3",
    explanation: "Total outcomes = 6.\nNumbers greater than 4 = {5, 6} (2 outcomes).\nProbability P = 2 / 6 = 1 / 3.",
    shortcut: "Outcomes {5,6} => 2/6 = 1/3.",
    company: "Tech Mahindra"
  },

  // === MEDIUM (Q11-Q25) ===
  {
    id: 6011,
    topic: "probability",
    difficulty: "medium",
    category: "Venn Diagram",
    q: "100 students appeared for two different examinations: 60 passed the first, 50 the second, and 30 passed both examinations. Find the probability that a student selected at random failed in both examinations.",
    options: ["A) 0.8", "B) 0.2", "C) 0.6", "D) 0.7"],
    answer: "B) 0.2",
    explanation: "Let A = passed first, B = passed second.\nP(A) = 60/100 = 0.6, P(B) = 50/100 = 0.5, P(A∩B) = 30/100 = 0.3.\nProbability of passing at least one exam: P(A∪B) = P(A) + P(B) - P(A∩B) = 0.6 + 0.5 - 0.3 = 0.8.\nProbability of failing both: P(failed both) = 1 - P(A∪B) = 1 - 0.8 = 0.2.",
    shortcut: "Passed either = 60 + 50 - 30 = 80%. Failed both = 100% - 80% = 20% = 0.2.",
    company: "TCS Ninja"
  },
  {
    id: 6012,
    topic: "probability",
    difficulty: "medium",
    category: "Bags",
    q: "A bag contains 8 white balls and 3 blue balls. Another bag contains 7 white and 4 blue balls. One bag is chosen at random and a ball is drawn from it. What is the probability of getting a blue ball?",
    options: ["A) 7/22", "B) 3/7", "C) 7/25", "D) 7/15"],
    answer: "A) 7/22",
    explanation: "Probability of choosing Bag 1 = 1/2. Probability of choosing Bag 2 = 1/2.\nP(Blue from Bag 1) = 3 / 11.\nP(Blue from Bag 2) = 4 / 11.\nCombined P(Blue) = P(Bag 1)*P(Blue|Bag 1) + P(Bag 2)*P(Blue|Bag 2) = (1/2 * 3/11) + (1/2 * 4/11) = 7/22.",
    shortcut: "Average of blue probabilities: (3/11 + 4/11) / 2 = 7/22.",
    company: "Infosys"
  },
  {
    id: 6013,
    topic: "probability",
    difficulty: "medium",
    category: "Bags",
    q: "There are two bags, one of which contains 5 red and 7 white balls and the other 3 red and 12 white balls. A ball is to be drawn from one or other of the two bags. Find the probability of drawing a red ball.",
    options: ["A) 37/120", "B) 55/102", "C) 17/21", "D) 7/8"],
    answer: "A) 37/120",
    explanation: "Probability of choosing either bag = 1/2.\nBag 1: Red = 5/12. Bag 2: Red = 3/15 = 1/5.\nCombined P(Red) = (1/2 * 5/12) + (1/2 * 1/5) = 5/24 + 1/10 = (25 + 12)/120 = 37/120.",
    shortcut: "P = 1/2 * (5/12 + 3/15) = 1/2 * (5/12 + 1/5) = 1/2 * 37/60 = 37/120.",
    company: "Wipro"
  },
  {
    id: 6014,
    topic: "probability",
    difficulty: "medium",
    category: "Calendar",
    q: "Find the probability that a leap year chosen at random will contain 53 Sundays.",
    options: ["A) 2/7", "B) 3/7", "C) 1/7", "D) 5/7"],
    answer: "A) 2/7",
    explanation: "Leap year = 366 days = 52 weeks + 2 extra days.\n52 weeks guarantee 52 Sundays. The 53rd Sunday depends on the 2 extra days.\nThe 7 possible consecutive pairs for the extra days are:\n{Sun-Mon, Mon-Tue, Tue-Wed, Wed-Thu, Thu-Fri, Fri-Sat, Sat-Sun}.\nTwo of these pairs contain a Sunday: {Sat-Sun} and {Sun-Mon}.\nTherefore, P = 2 / 7.",
    shortcut: "Leap year extra days = 2. Total days in week = 7. P = 2/7.",
    company: "Accenture"
  },
  {
    id: 6015,
    topic: "probability",
    difficulty: "medium",
    category: "Complementary Independent",
    q: "A problem is given to three students whose chances of solving it are 1/2, 1/3, and 1/4 respectively. What is the probability that the problem will be solved?",
    options: ["A) 1/4", "B) 1/2", "C) 3/4", "D) 7/12"],
    answer: "C) 3/4",
    explanation: "Let the events be A, B, C.\nP(A') = 1 - 1/2 = 1/2.\nP(B') = 1 - 1/3 = 2/3.\nP(C') = 1 - 1/4 = 3/4.\nProbability that NONE of them solves the problem: P(none) = 1/2 * 2/3 * 3/4 = 6/24 = 1/4.\nProbability that the problem is solved = 1 - P(none) = 1 - 1/4 = 3/4.",
    shortcut: "P(solved) = 1 - (1/2 * 2/3 * 3/4) = 1 - 1/4 = 3/4.",
    company: "Capgemini"
  },
  {
    id: 6016,
    topic: "probability",
    difficulty: "medium",
    category: "Dice Sum",
    q: "Two dice are tossed. The probability that the total score is a prime number is?",
    options: ["A) 5/12", "B) 1/6", "C) 1/2", "D) 7/9"],
    answer: "A) 5/12",
    explanation: "Total outcomes for two dice n(S) = 36.\nPrime sums possible are 2, 3, 5, 7, and 11.\n- Sum = 2: {(1,1)} (1 outcome)\n- Sum = 3: {(1,2), (2,1)} (2 outcomes)\n- Sum = 5: {(1,4), (2,3), (3,2), (4,1)} (4 outcomes)\n- Sum = 7: {(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)} (6 outcomes)\n- Sum = 11: {(5,6), (6,5)} (2 outcomes)\nTotal favorable outcomes = 1 + 2 + 4 + 6 + 2 = 15.\nProbability P = 15 / 36 = 5 / 12.",
    shortcut: "Favorable sum count = 15. 15/36 = 5/12.",
    company: "Cognizant"
  },
  {
    id: 6017,
    topic: "probability",
    difficulty: "medium",
    category: "Conditional Probability",
    q: "If two dice are rolled together, find the probability that the total of the two dice will be greater than 8, given that the first die shows a 6.",
    options: ["A) 1/2", "B) 2/5", "C) 2/3", "D) 1/9"],
    answer: "C) 2/3",
    explanation: "Since the first die is fixed as 6, the reduced sample space is:\nS = {(6,1), (6,2), (6,3), (6,4), (6,5), (6,6)} (n(S) = 6).\nFavorable outcomes (sum > 8): {(6,3), (6,4), (6,5), (6,6)} (4 outcomes).\nProbability P = 4 / 6 = 2 / 3.",
    shortcut: "First die is 6. Second die must be 3, 4, 5, or 6 to get sum > 8. 4 choices out of 6 => 4/6 = 2/3.",
    company: "Deloitte"
  },
  {
    id: 6018,
    topic: "probability",
    difficulty: "medium",
    category: "Basketball",
    q: "In a group of 80 men and 40 women, half of the total men and half of the total women know basketball. Find the probability of choosing one man or woman who knows basketball.",
    options: ["A) 2/3", "B) 1/2", "C) 14/7", "D) 16/9"],
    answer: "B) 1/2",
    explanation: "Total group size = 80 + 40 = 120.\nMen knowing basketball = 80 * 1/2 = 40.\nWomen knowing basketball = 40 * 1/2 = 20.\nTotal people knowing basketball = 40 + 20 = 60.\nProbability of choosing someone who knows basketball = 60 / 120 = 1/2.",
    shortcut: "Since exactly half of each group knows basketball, overall exactly half of the total group knows basketball => 1/2.",
    company: "Infosys"
  },
  {
    id: 6019,
    topic: "probability",
    difficulty: "medium",
    category: "Coins",
    q: "Two coins are tossed simultaneously. Find the probability of getting at least one head.",
    options: ["A) 1/4", "B) 1/2", "C) 3/4", "D) 1"],
    answer: "C) 3/4",
    explanation: "Sample space = {HH, HT, TH, TT} (4 outcomes).\nFavorable outcomes (at least one head) = {HH, HT, TH} (3 outcomes).\nProbability P = 3/4.",
    shortcut: "P(at least one head) = 1 - P(no heads, i.e., TT) = 1 - 1/4 = 3/4.",
    company: "TCS Ninja"
  },
  {
    id: 6020,
    topic: "probability",
    difficulty: "medium",
    category: "Cards",
    q: "A card is drawn from a pack of 52 cards. Find the probability that it is either a king or a queen.",
    options: ["A) 1/13", "B) 2/13", "C) 1/26", "D) 4/13"],
    answer: "B) 2/13",
    explanation: "Total cards = 52.\nKings = 4, Queens = 4 (mutually exclusive events).\nFavorable outcomes = 4 + 4 = 8.\nProbability P = 8 / 52 = 2 / 13.",
    shortcut: "4/52 (King) + 4/52 (Queen) = 8/52 = 2/13.",
    company: "Accenture"
  },
  {
    id: 6021,
    topic: "probability",
    difficulty: "medium",
    category: "Coins",
    q: "Three coins are tossed together. Find the probability of getting exactly two heads.",
    options: ["A) 1/8", "B) 3/8", "C) 1/2", "D) 5/8"],
    answer: "B) 3/8",
    explanation: "Sample space = {HHH, HHT, HTH, HTT, THH, THT, TTH, TTT} (8 outcomes).\nFavorable outcomes (exactly two heads) = {HHT, HTH, THH} (3 outcomes).\nProbability P = 3 / 8.",
    shortcut: "Favorable count is 3 out of 8 => 3/8.",
    company: "Tech Mahindra"
  },
  {
    id: 6022,
    topic: "probability",
    difficulty: "medium",
    category: "Ball Drawings",
    q: "A bag contains 5 red, 4 blue, and 3 green balls. One ball is drawn at random. Find the probability that it is either red or green.",
    options: ["A) 1/3", "B) 1/2", "C) 2/3", "D) 3/4"],
    answer: "C) 2/3",
    explanation: "Total balls = 5 + 4 + 3 = 12.\nFavorable (red or green) balls = 5 + 3 = 8.\nProbability P = 8 / 12 = 2 / 3.",
    shortcut: "Favorable/Total = 8/12 = 2/3.",
    company: "Wipro"
  },
  {
    id: 6023,
    topic: "probability",
    difficulty: "medium",
    category: "Primes",
    q: "A number is selected at random from 1 to 25. Find the probability that it is a prime number.",
    options: ["A) 7/25", "B) 8/25", "C) 9/25", "D) 10/25"],
    answer: "C) 9/25",
    explanation: "Total numbers = 25.\nPrime numbers from 1 to 25 are: 2, 3, 5, 7, 11, 13, 17, 19, 23 (9 numbers total).\nProbability P = 9 / 25.",
    shortcut: "Count primes: 9. P = 9/25.",
    company: "Cognizant"
  },
  {
    id: 6024,
    topic: "probability",
    difficulty: "medium",
    category: "Dice Sum",
    q: "Two dice are thrown together. Find the probability that the sum is either 7 or 11.",
    options: ["A) 1/6", "B) 2/9", "C) 5/18", "D) 1/4"],
    answer: "B) 2/9",
    options: ["A) 1/6", "B) 2/9", "C) 5/18", "D) 1/4"],
    answer: "B) 2/9",
    explanation: "Total outcomes n(S) = 36.\n- Sum = 7: {(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)} (6 outcomes).\n- Sum = 11: {(5,6), (6,5)} (2 outcomes).\nCombined favorable outcomes = 6 + 2 = 8.\nProbability P = 8 / 36 = 2 / 9.",
    shortcut: "8/36 = 2/9.",
    company: "TCS Ninja"
  },
  {
    id: 6025,
    topic: "probability",
    difficulty: "medium",
    category: "Venn Diagram",
    q: "In a class of 60 students, 40 play cricket, 30 play football, and 20 play both games. Find the probability that a randomly selected student plays neither game.",
    options: ["A) 1/6", "B) 1/3", "C) 1/2", "D) 2/3"],
    answer: "A) 1/6",
    explanation: "Let C = play cricket, F = play football.\nTotal students = 60.\nStudents playing either cricket or football: n(C∪F) = n(C) + n(F) - n(C∩F) = 40 + 30 - 20 = 50.\nStudents playing neither game = 60 - 50 = 10.\nProbability P = 10 / 60 = 1 / 6.",
    shortcut: "Union = 40 + 30 - 20 = 50. Neither = 60 - 50 = 10. P = 10/60 = 1/6.",
    company: "Infosys"
  },

  // === HARD (Q26-Q40) ===
  {
    id: 6026,
    topic: "probability",
    difficulty: "hard",
    category: "Ball Drawings",
    q: "A bag contains 6 white, 5 red, and 4 blue balls. Three balls are drawn at random. What is the probability that all three are red?",
    options: ["A) 1/22", "B) 3/22", "C) 2/91", "D) 2/77"],
    answer: "C) 2/91",
    explanation: "Total balls = 6 + 5 + 4 = 15.\nTotal ways to draw 3 balls from 15 = ¹⁵C₃ = (15 * 14 * 13) / (3 * 2 * 1) = 455.\nWays to draw 3 red balls from 5 red = ⁵C₃ = ⁵C₂ = (5 * 4) / 2 = 10.\nProbability P = 10 / 455 = 2 / 91.",
    shortcut: "P = (5/15) * (4/14) * (3/13) = (1/3) * (2/7) * (3/13) = 2/91.",
    company: "Google, TCS Digital"
  },
  {
    id: 6027,
    topic: "probability",
    difficulty: "hard",
    category: "Recurring Events",
    q: "On a toss of two dice, A throws a total of 5. Then the probability that he will throw another 5 before he throws a 7 is?",
    options: ["A) 0.50", "B) 0.45", "C) 0.40", "D) 0.60"],
    answer: "C) 0.40",
    explanation: "P(sum=5) = 4 / 36 = 1/9. (Outcomes: (1,4), (2,3), (3,2), (4,1))\nP(sum=7) = 6 / 36 = 1/6. (Outcomes: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1))\nSince we only care about getting a 5 or a 7 first, we can ignore all other sums.\nProbability of throwing a 5 before a 7 = P(5) / [P(5) + P(7)] = (1/9) / (1/9 + 1/6) = (1/9) / (5/18) = (1/9) * (18/5) = 2/5 = 0.40.",
    shortcut: "Favorable sum 5 has 4 outcomes, sum 7 has 6. P = 4 / (4 + 6) = 4/10 = 0.40.",
    company: "Goldman Sachs"
  },
  {
    id: 6028,
    topic: "probability",
    difficulty: "hard",
    category: "Combinatorics Circle",
    q: "There are 20 persons sitting in a circle, of whom 18 are men and 2 are sisters. How many arrangements are possible in which the two sisters are always separated by a man (i.e., seated with exactly one man between them)?",
    options: ["A) 12", "B) 17 × 2!", "C) 17!", "D) 18! × 2"],
    answer: "D) 18! × 2",
    explanation: "Seat the 18 men first in a circle. This can be done in (18 - 1)! = 17! ways.\nThis leaves 18 gaps between the men.\nFor the sisters to be separated by exactly one man, they must choose two gaps that are adjacent (i.e., separated by exactly one man's seat).\nThere are exactly 18 such pairs of adjacent gaps in a circular arrangement of 18 seats.\nThe sisters can occupy these two seats in 2! = 2 ways.\nTotal valid arrangements = 17! * 18 * 2 = 18! * 2.",
    shortcut: "Circular permutation of men (17!). Gaps adjacent selection: 18 * 2! = 18 * 2. Total = 18! * 2.",
    company: "Amazon"
  },
  {
    id: 6029,
    topic: "probability",
    difficulty: "hard",
    category: "Combinatorics Cases",
    q: "In how many ways can a team of 11 be selected from a pool of 5 men and 11 women, such that the team must comprise not more than 3 men?",
    options: ["A) 2255", "B) 2256", "C) 2258", "D) 2259"],
    answer: "B) 2256",
    explanation: "We sum up the combinations for each valid case (0, 1, 2, or 3 men):\n- Case 1: 0 Men, 11 Women: ⁵C₀ * ¹¹C₁₁ = 1 * 1 = 1.\n- Case 2: 1 Man, 10 Women: ⁵C₁ * ¹¹C₁₀ = 5 * 11 = 55.\n- Case 3: 2 Men, 9 Women: ⁵C₂ * ¹¹C₉ = 10 * 55 = 550.\n- Case 4: 3 Men, 8 Women: ⁵C₃ * ¹¹C₈ = 10 * 165 = 1650.\nTotal ways = 1 + 55 + 550 + 1650 = 2256.",
    shortcut: "⁵C₀*¹¹C₁₁ + ⁵C₁*¹¹C₁₀ + ⁵C₂*¹¹C₉ + ⁵C₃*¹¹C₈ = 1 + 55 + 550 + 1650 = 2256.",
    company: "TCS Digital"
  },
  {
    id: 6030,
    topic: "probability",
    difficulty: "hard",
    category: "Conditional Cards",
    q: "One card is lost out of 52 cards. Two cards are drawn randomly from the remaining 51 cards, and they turn out to be spades. What is the probability that the lost card is also a spade?",
    options: ["A) 1/52", "B) 1/13", "C) 1/4", "D) 11/50"],
    answer: "D) 11/50",
    explanation: "Let the lost card be a spade (event L). We know that two spades are drawn from the remaining cards.\nOnce 2 spade cards are drawn, the remaining pool consists of 50 cards.\nOut of these 50 cards, if the lost card was a spade, there would have been 13 spades originally. Since 2 are drawn, 11 spades remain.\nThus, the probability that the lost card is a spade, given two spades are drawn, is 11 / 50.",
    shortcut: "Once 2 spades are drawn, 50 cards remain. Probability of lost card being spade is the remaining spades count divided by remaining cards: 11 / 50.",
    company: "Microsoft"
  },
  {
    id: 6031,
    topic: "probability",
    difficulty: "hard",
    category: "Cards",
    q: "From a pack of 52 cards, two cards are drawn at random. Find the probability that both are aces.",
    options: ["A) 1/221", "B) 1/26", "C) 1/13", "D) 4/221"],
    answer: "A) 1/221",
    explanation: "Total ways to draw 2 cards = ⁵²C₂ = (52 * 51) / 2 = 1326.\nWays to draw 2 aces (out of 4) = ⁴C₂ = (4 * 3) / 2 = 6.\nProbability P = 6 / 1326 = 1 / 221.",
    shortcut: "P = (4/52) * (3/51) = (1/13) * (1/17) = 1/221.",
    company: "Wipro"
  },
  {
    id: 6032,
    topic: "probability",
    difficulty: "hard",
    category: "Ball Drawings",
    q: "A bag contains 5 white and 7 black balls. Two balls are drawn at random without replacement. Find the probability that both are black.",
    options: ["A) 5/22", "B) 7/22", "C) 7/12", "D) 5/12"],
    answer: "B) 7/22",
    explanation: "Total balls = 12.\nTotal ways to draw 2 balls = ¹²C₂ = (12 * 11) / 2 = 66.\nWays to draw 2 black balls (out of 7) = ⁷C₂ = (7 * 6) / 2 = 21.\nProbability P = 21 / 66 = 7 / 22.",
    shortcut: "P = (7/12) * (6/11) = 7/22.",
    company: "Infosys"
  },
  {
    id: 6033,
    topic: "probability",
    difficulty: "hard",
    category: "Cards",
    q: "Three cards are drawn from a well-shuffled pack of 52 cards. Find the probability that all three are kings.",
    options: ["A) 1/5525", "B) 1/2197", "C) 4/5525", "D) 1/1000"],
    answer: "A) 1/5525",
    explanation: "Total ways to draw 3 cards = ⁵²C₃ = (52 * 51 * 50) / (3 * 2 * 1) = 22100.\nWays to draw 3 kings (out of 4) = ⁴C₃ = 4.\nProbability P = 4 / 22100 = 1 / 5525.",
    shortcut: "P = (4/52) * (3/51) * (2/50) = (1/13) * (1/17) * (1/25) = 1 / 5525.",
    company: "Deloitte"
  },
  {
    id: 6034,
    topic: "probability",
    difficulty: "hard",
    category: "Lottery",
    q: "In a lottery, there are 10 prizes and 25 blanks. A ticket is drawn at random. What is the probability of getting a prize?",
    options: ["A) 1/7", "B) 2/7", "C) 3/7", "D) 5/7"],
    answer: "B) 2/7",
    explanation: "Total tickets = 10 + 25 = 35.\nPrizes = 10.\nProbability P = 10 / 35 = 2 / 7.",
    shortcut: "10/35 = 2/7.",
    company: "Accenture"
  },
  {
    id: 6035,
    topic: "probability",
    difficulty: "hard",
    category: "Committee Selection",
    q: "A committee of 3 members is to be selected from a group of 5 men and 4 women. Find the probability that the committee has exactly 2 men and 1 woman.",
    options: ["A) 5/21", "B) 10/21", "C) 4/21", "D) 5/14"],
    answer: "B) 10/21",
    explanation: "Total people = 9. Total committees of size 3 = ⁹C₃ = (9 * 8 * 7) / (3 * 2 * 1) = 84.\nFavorable committees (2 men out of 5, 1 woman out of 4) = ⁵C₂ * ⁴C₁ = 10 * 4 = 40.\nProbability P = 40 / 84 = 10 / 21.",
    shortcut: "⁵C₂ * ⁴C₁ / ⁹C₃ = 10 * 4 / 84 = 40/84 = 10/21.",
    company: "Capgemini"
  },
  {
    id: 6036,
    topic: "probability",
    difficulty: "hard",
    category: "Dice Product",
    q: "Two dice are thrown simultaneously. Find the probability that the product of the numbers on the two dice is a multiple of 3.",
    options: ["A) 1/3", "B) 4/9", "C) 5/9", "D) 2/3"],
    answer: "C) 5/9",
    explanation: "Total outcomes = 36.\nFor the product to NOT be a multiple of 3, neither die can show a multiple of 3.\nNumbers not multiples of 3 on a die are {1, 2, 4, 5} (4 numbers).\nOutcomes where neither is a multiple of 3 = 4 * 4 = 16 outcomes.\nFavorable outcomes (product is a multiple of 3) = 36 - 16 = 20.\nProbability P = 20 / 36 = 5 / 9.",
    shortcut: "1 - P(neither is multiple of 3) = 1 - (4/6 * 4/6) = 1 - 4/9 = 5/9.",
    company: "Cognizant"
  },
  {
    id: 6037,
    topic: "probability",
    difficulty: "hard",
    category: "Ball Drawings",
    q: "A box contains 6 red, 4 blue, and 5 green marbles. Two marbles are drawn at random without replacement. Find the probability that both are of the same colour.",
    options: ["A) 29/105", "B) 31/105", "C) 33/105", "D) 35/105"],
    answer: "B) 31/105",
    explanation: "Total marbles = 6 + 4 + 5 = 15. Total ways to draw 2 marbles = ¹⁵C₂ = 105.\nFavorable ways (same color):\n- Both red: ⁶C₂ = 15\n- Both blue: ⁴C₂ = 6\n- Both green: ⁵C₂ = 10\nTotal favorable ways = 15 + 6 + 10 = 31.\nProbability P = 31 / 105.",
    shortcut: "⁶C₂ + ⁴C₂ + ⁵C₂ / ¹⁵C₂ = (15 + 6 + 10) / 105 = 31/105.",
    company: "Wipro"
  },
  {
    id: 6038,
    topic: "probability",
    difficulty: "hard",
    category: "Committee Selection",
    q: "From a group of 6 boys and 4 girls, a committee of 4 is to be formed. Find the probability that the committee has at least one girl.",
    options: ["A) 11/14", "B) 12/14", "C) 13/14", "D) 9/10"],
    answer: "C) 13/14",
    explanation: "Total ways to form a committee of 4 from 10 = ¹⁰C₄ = 210.\nWays to form a committee with NO girls (all boys) = ⁶C₄ = 15.\nProbability of no girls = 15 / 210 = 1 / 14.\nProbability of at least one girl = 1 - 1/14 = 13/14.",
    shortcut: "P(at least one girl) = 1 - ⁶C₄ / ¹⁰C₄ = 1 - 15/210 = 1 - 1/14 = 13/14.",
    company: "Infosys"
  },
  {
    id: 6039,
    topic: "probability",
    difficulty: "hard",
    category: "Cards",
    q: "Four cards are drawn at random from a pack of 52 cards. Find the probability that all four are of the same suit.",
    options: ["A) 44/4165", "B) 1/100", "C) 13/850", "D) 1/50"],
    answer: "A) 44/4165",
    explanation: "Total ways to draw 4 cards from 52 = ⁵²C₄ = 270725.\nFavorable ways (all four from the same suit):\nThere are 4 suits, and from each suit we choose 4 cards: 4 * ¹³C₄ = 4 * 715 = 2860.\nProbability P = 2860 / 270725 = 44 / 4165.",
    shortcut: "P = 4 * (13/52 * 12/51 * 11/50 * 10/49) = 4 * 11/4165 = 44/4165.",
    company: "TCS Digital"
  },
  {
    id: 6040,
    topic: "probability",
    difficulty: "hard",
    category: "Contradiction",
    q: "A speaks the truth 3 out of 4 times, and B speaks the truth 5 out of 6 times. Find the probability that they contradict each other in stating the same fact.",
    options: ["A) 1/4", "B) 1/3", "C) 5/12", "D) 1/2"],
    answer: "B) 1/3",
    explanation: "Let T_A = A speaks truth, T_B = B speaks truth.\nP(T_A) = 3/4, P(T_A') = 1/4.\nP(T_B) = 5/6, P(T_B') = 1/6.\nContradiction occurs when A speaks truth & B lies, or A lies & B speaks truth:\nP(contradiction) = P(T_A)*P(T_B') + P(T_A')*P(T_B) = (3/4 * 1/6) + (1/4 * 5/6) = 3/24 + 5/24 = 8/24 = 1/3.",
    shortcut: "P = 3/4 * 1/6 + 1/4 * 5/6 = 3/24 + 5/24 = 8/24 = 1/3.",
    company: "Google, TCS Ninja"
  }
];
