export const problemsAgesQuizQuestions = [
  // === EASY (Q1-Q10) ===
  {
    id: 5001,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Basic Ratios",
    q: "At present, the ratio between the ages of Amit and Dhiraj is 5:4. After 6 years, Amit's age will be 26 years. What is the age of Dhiraj at present?",
    options: ["A) 12 years", "B) 16 years", "C) 17 years", "D) 21 years"],
    answer: "B) 16 years",
    explanation: "Let Amit's present age be 5x and Dhiraj's be 4x.\nAfter 6 years Amit will be 26: 5x + 6 = 26 => 5x = 20 => x = 4.\nDhiraj's present age = 4x = 4(4) = 16 years.",
    shortcut: "Solve for x from the known person (Amit): 26 - 6 = 20 => 20/5 = 4. Dhiraj = 4 * 4 = 16.",
    company: "TCS, Infosys"
  },
  {
    id: 5002,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Sum Difference",
    q: "The sum of the ages of A and B is 12 years more than the sum of the ages of B and C. How many years younger than A is C?",
    options: ["A) 12 years", "B) 13 years", "C) 14 years", "D) 15 years"],
    answer: "A) 12 years",
    explanation: "Given: (A + B) - (B + C) = 12.\nExpanding the expression: A + B - B - C = 12 => A - C = 12.\nSo, C is 12 years younger than A.",
    shortcut: "The common term (B) cancels out automatically, leaving A - C = 12.",
    company: "Wipro, Cognizant"
  },
  {
    id: 5003,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Fractions",
    q: "A person's present age is two-fifths of the age of his mother. After 8 years, he will be one-half of the age of his mother. How old is the mother at present?",
    options: ["A) 36 years", "B) 40 years", "C) 44 years", "D) 42 years"],
    answer: "B) 40 years",
    explanation: "Let the mother's present age be x. Then the person's present age is 2x/5.\nAfter 8 years: (2x/5) + 8 = 1/2 * (x + 8)\nMultiply by 10 to clear fractions: 4x + 80 = 5(x + 8) => 4x + 80 = 5x + 40 => x = 40.\nSo, the mother's present age is 40 years.",
    shortcut: "Clear fractions by cross-multiplying immediately.",
    company: "Accenture, Capgemini"
  },
  {
    id: 5004,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Future Multiples",
    q: "Ravi's present age is 25 years and his son's present age is 5 years. In how many years will Ravi's age be three times his son's age?",
    options: ["A) 4 years", "B) 5 years", "C) 6 years", "D) 7 years"],
    answer: "B) 5 years",
    explanation: "Let the number of years be n.\n25 + n = 3(5 + n) => 25 + n = 15 + 3n => 10 = 2n => n = 5.\nSo, in 5 years Ravi's age will be 3 times his son's.",
    shortcut: "Test options: In 5 years, Ravi is 30, son is 10. 30 = 3 * 10. Matches!",
    company: "TCS Ninja"
  },
  {
    id: 5005,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Basic Ratios",
    q: "The ratio of the ages of two brothers is 3:5. If the sum of their ages is 48 years, find the age of the younger brother.",
    options: ["A) 15 years", "B) 18 years", "C) 20 years", "D) 24 years"],
    answer: "B) 18 years",
    explanation: "Let the ages of the two brothers be 3x and 5x.\n3x + 5x = 48 => 8x = 48 => x = 6.\nYounger brother's age = 3x = 3(6) = 18 years.",
    shortcut: "Younger age = 48 * (3 / 8) = 18.",
    company: "Infosys, Wipro"
  },
  {
    id: 5006,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Difference and Past Multiple",
    q: "Sita is 6 years older than Geeta. Ten years ago, Sita was twice as old as Geeta. Find Geeta's present age.",
    options: ["A) 14 years", "B) 16 years", "C) 18 years", "D) 20 years"],
    answer: "B) 16 years",
    explanation: "Let Geeta's present age be x. Sita's present age is x + 6.\nTen years ago: Sita was (x + 6 - 10) = x - 4, Geeta was x - 10.\nEquation: x - 4 = 2(x - 10) => x - 4 = 2x - 20 => x = 16.\nGeeta's present age is 16 years.",
    shortcut: "Difference is always 6. If Sita was twice Geeta, then Geeta was 6 and Sita was 12. Geeta present = 6 + 10 = 16.",
    company: "Tech Mahindra"
  },
  {
    id: 5007,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Sum and Past Ratio",
    q: "The sum of the present ages of P and Q is 42 years. Six years ago, P's age was twice Q's age. Find Q's present age.",
    options: ["A) 14 years", "B) 16 years", "C) 18 years", "D) 20 years"],
    answer: "B) 16 years",
    explanation: "Let Q's present age be x. Then P's present age is 42 - x.\nSix years ago: P was 42 - x - 6 = 36 - x, Q was x - 6.\nEquation: 36 - x = 2(x - 6) => 36 - x = 2x - 12 => 3x = 48 => x = 16.\nQ's present age is 16 years.",
    shortcut: "Sum 6 years ago = 42 - 12 = 30. Ratio 2:1 => Q 6 years ago = 30 * 1/3 = 10. Q present = 10 + 6 = 16.",
    company: "L&T Infotech"
  },
  {
    id: 5008,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Fractions",
    q: "A boy's age is one-third of his father's age. If the father's age is 45 years, find the boy's age.",
    options: ["A) 12 years", "B) 15 years", "C) 18 years", "D) 20 years"],
    answer: "B) 15 years",
    explanation: "Boy's age = 1/3 * Father's age = 1/3 * 45 = 15 years.",
    shortcut: "45 ÷ 3 = 15.",
    company: "Infosys"
  },
  {
    id: 5009,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Past Multiples",
    q: "Meena's daughter is presently 20 years old. Ten years ago, Meena's age was thrice her daughter's age at that time. What is Meena's present age?",
    options: ["A) 35 years", "B) 38 years", "C) 40 years", "D) 42 years"],
    answer: "C) 40 years",
    explanation: "Daughter's age 10 years ago = 20 - 10 = 10 years.\nMeena's age 10 years ago = 3 * 10 = 30 years.\nMeena's present age = 30 + 10 = 40 years.",
    shortcut: "Daughter then = 10 => Meena then = 30 => Present = 40.",
    company: "Cognizant"
  },
  {
    id: 5010,
    topic: "problems-ages",
    difficulty: "easy",
    category: "Multiple Relation",
    q: "The present age of a mother is 4 times her daughter's age. After 5 years, the mother's age will be thrice the daughter's age. Find the daughter's present age.",
    options: ["A) 8 years", "B) 10 years", "C) 12 years", "D) 15 years"],
    answer: "B) 10 years",
    explanation: "Let the daughter's present age be x. Mother's present age = 4x.\nAfter 5 years: 4x + 5 = 3(x + 5) => 4x + 5 = 3x + 15 => x = 10.\nDaughter's present age is 10 years.",
    shortcut: "4x + 5 = 3x + 15 => x = 10.",
    company: "Accenture"
  },

  // === MEDIUM (Q11-Q25) ===
  {
    id: 5011,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Past Ratios",
    q: "The present ages of Nina and Aman are 37 years and 59 years, respectively. What was the ratio of their ages 13 years ago?",
    options: ["A) 2:3", "B) 12:23", "C) 46:25", "D) 8:3"],
    answer: "B) 12:23",
    explanation: "Nina's age 13 years ago = 37 - 13 = 24 years.\nAman's age 13 years ago = 59 - 13 = 46 years.\nRatio = 24 : 46 = 12 : 23.",
    shortcut: "24/46 simplified is 12/23.",
    company: "TCS Ninja"
  },
  {
    id: 5012,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Future Ratios",
    q: "The present ages of A and B are 42 and 36 years, respectively. After K years, the ratio of ages of B to A will be 15:17. Find K.",
    options: ["A) 7", "B) 8", "C) 9", "D) 10"],
    answer: "C) 9",
    explanation: "After K years: B's age = 36 + K, A's age = 42 + K.\nEquation: (36 + K) / (42 + K) = 15 / 17\n17(36 + K) = 15(42 + K) => 612 + 17K = 630 + 15K => 2K = 18 => K = 9.",
    shortcut: "Test options: K = 9 => B = 45, A = 51. 45:51 = 15:17. Correct!",
    company: "Wipro"
  },
  {
    id: 5013,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Difference and Past Multiple",
    q: "A is 16 years older than Ramesh. A's present age is 5 times Ramesh's age 4 years ago. What is Ramesh's present age?",
    options: ["A) 9 years", "B) 13 years", "C) 16 years", "D) 21 years"],
    answer: "A) 9 years",
    explanation: "Let Ramesh's present age be x. A's present age = x + 16.\nGiven: x + 16 = 5(x - 4) => x + 16 = 5x - 20 => 36 = 4x => x = 9.\nRamesh's present age is 9 years.",
    shortcut: "x + 16 = 5x - 20 => 4x = 36 => x = 9.",
    company: "Cognizant"
  },
  {
    id: 5014,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Double Shift Condition",
    q: "Neha's mother was four times her age 12 years ago. She will be twice as old as Neha 12 years from now. What is the present age of Neha's mother?",
    options: ["A) 50 years", "B) 40 years", "C) 60 years", "D) 45 years"],
    answer: "C) 60 years",
    explanation: "Let Neha's age 12 years ago be x. Mother's age then = 4x.\nPresent ages: Neha = x + 12, Mother = 4x + 12.\nAges 12 years from now: Neha = x + 24, Mother = 4x + 24.\nEquation: 4x + 24 = 2(x + 24) => 4x + 24 = 2x + 48 => 2x = 24 => x = 12.\nMother's present age = 4x + 12 = 4(12) + 12 = 60 years.",
    shortcut: "Mother = 4x + 12. Check options. 60 => x = 12. Neha 12 yrs ago = 12. In 12 yrs, Neha is 36, Mother is 72. Twice as old. Matches!",
    company: "Accenture"
  },
  {
    id: 5015,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Future Ratios",
    q: "Present ages of Sameer and Anand are in ratio 5:4. Three years hence, ratio will be 11:9. Find Anand's present age.",
    options: ["A) 24 years", "B) 28 years", "C) 32 years", "D) 36 years"],
    answer: "A) 24 years",
    explanation: "Let present ages be 5x and 4x.\nThree years hence: (5x + 3)/(4x + 3) = 11/9\n9(5x + 3) = 11(4x + 3) => 45x + 27 = 44x + 33 => x = 6.\nAnand's present age = 4x = 4(6) = 24 years.",
    shortcut: "Test options for Anand: If Anand = 24, Sameer = 30. After 3 years: 33:27 = 11:9. Matches!",
    company: "Infosys"
  },
  {
    id: 5016,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Sum and Past Ratio",
    q: "The sum of the present ages of a father and his son is 60 years. Six years ago, the father's age was five times the age of the son. After 6 years, what will the son's age be?",
    options: ["A) 12 years", "B) 14 years", "C) 18 years", "D) 20 years"],
    answer: "D) 20 years",
    explanation: "Let son's present age be x. Father's present age = 60 - x.\nSix years ago: (60 - x - 6) = 5(x - 6) => 54 - x = 5x - 30 => 6x = 84 => x = 14.\nSon's age after 6 years = 14 + 6 = 20 years.",
    shortcut: "Sum 6 years ago = 60 - 12 = 48. Ratio 5:1 => Son then = 48/6 = 8. Son present = 14 => after 6 yrs = 20.",
    company: "Capgemini"
  },
  {
    id: 5017,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Past Multiples",
    q: "The age of a man is 4 times that of his son. Five years ago, the man was nine times as old as his son was at that time. What is the present age of the man?",
    options: ["A) 32 years", "B) 34 years", "C) 42 years", "D) 47 years"],
    answer: "A) 32 years",
    explanation: "Let son's present age be x. Man's present age = 4x.\nFive years ago: 4x - 5 = 9(x - 5) => 4x - 5 = 9x - 45 => 5x = 40 => x = 8.\nMan's present age = 4x = 4(8) = 32 years.",
    shortcut: "4x - 5 = 9x - 45 => 5x = 40 => x = 8 => Man = 32.",
    company: "Wipro"
  },
  {
    id: 5018,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Ratios and Difference",
    q: "Sachin is younger than Rahul by 7 years. If the ratio of their ages is 7:9, find the present age of Sachin.",
    options: ["A) 24.5 years", "B) 26 years", "C) 28 years", "D) 31.5 years"],
    answer: "A) 24.5 years",
    explanation: "Let ages be 7x and 9x. Difference = 9x - 7x = 2x.\nGiven 2x = 7 => x = 3.5.\nSachin's present age = 7x = 7(3.5) = 24.5 years.",
    shortcut: "Difference of parts = 2. 2 parts = 7 years => 1 part = 3.5. Sachin = 7 * 3.5 = 24.5.",
    company: "TCS Ninja"
  },
  {
    id: 5019,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Unit Conversion Ratios",
    q: "The ratio of the ages of Maala and Kala is 4:3. The total of their ages is 2.8 decades. What will be the ratio of their ages after 0.8 decades? (1 Decade = 10 years)",
    options: ["A) 4:3", "B) 12:11", "C) 7:4", "D) 6:5"],
    answer: "D) 6:5",
    explanation: "Total age = 2.8 * 10 = 28 years.\nLet ages be 4x and 3x. 4x + 3x = 28 => 7x = 28 => x = 4.\nMaala = 16 years, Kala = 12 years.\nAfter 0.8 decades (8 years): Maala = 16 + 8 = 24, Kala = 12 + 8 = 20.\nRatio = 24 : 20 = 6 : 5.",
    shortcut: "Total = 28. Maala = 16, Kala = 12. Add 8: 24:20 = 6:5.",
    company: "Infosys"
  },
  {
    id: 5020,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Future Ratios",
    q: "The ages of two friends A and B are in the ratio 4:5. Eight years hence, their ages will be in the ratio 5:6. Find A's present age.",
    options: ["A) 28 years", "B) 30 years", "C) 32 years", "D) 36 years"],
    answer: "C) 32 years",
    explanation: "Let ages be 4x and 5x.\nAfter 8 years: (4x + 8)/(5x + 8) = 5/6\n6(4x + 8) = 5(5x + 8) => 24x + 48 = 25x + 40 => x = 8.\nA's present age = 4x = 4(8) = 32 years.",
    shortcut: "Ratio increases by 1 part (4 to 5, and 5 to 6) in 8 years. So 1 part = 8 years. A's present = 4 parts = 32.",
    company: "Accenture"
  },
  {
    id: 5021,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Future Multiples",
    q: "A father's age is three times his son's age. After 12 years, the father's age will be twice his son's age. Find the father's present age.",
    options: ["A) 30 years", "B) 33 years", "C) 36 years", "D) 40 years"],
    answer: "C) 36 years",
    explanation: "Let son's age be x. Father's age = 3x.\nAfter 12 years: 3x + 12 = 2(x + 12) => 3x + 12 = 2x + 24 => x = 12.\nFather's present age = 3x = 3(12) = 36 years.",
    shortcut: "3x + 12 = 2x + 24 => x = 12 => Father = 36.",
    company: "Cognizant"
  },
  {
    id: 5022,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Sum and Future Multiple",
    q: "The sum of the ages of a father and son is 56 years. After 4 years, the father's age will be three times that of his son. Find the son's present age.",
    options: ["A) 10 years", "B) 12 years", "C) 14 years", "D) 16 years"],
    answer: "B) 12 years",
    explanation: "Let son's present age be x. Father's present age = 56 - x.\nAfter 4 years: Father = 56 - x + 4 = 60 - x, Son = x + 4.\nEquation: 60 - x = 3(x + 4) => 60 - x = 3x + 12 => 4x = 48 => x = 12.\nSon's present age is 12 years.",
    shortcut: "Sum in 4 years = 56 + 8 = 64. Ratio 3:1 => Son then = 64/4 = 16. Son present = 16 - 4 = 12.",
    company: "Wipro"
  },
  {
    id: 5023,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Simultaneous Equations",
    q: "Two years ago, a father was 5 times as old as his son. Two years hence, his age will be 8 more than three times the age of his son. Find the father's present age.",
    options: ["A) 38 years", "B) 40 years", "C) 42 years", "D) 45 years"],
    answer: "C) 42 years",
    explanation: "Let father's age be y, son's age be x.\n2 years ago: y - 2 = 5(x - 2) => y = 5x - 8  (Eqn 1)\n2 years hence: y + 2 = 3(x + 2) + 8 => y = 3x + 12 (Eqn 2)\nEquating Eqns: 5x - 8 = 3x + 12 => 2x = 20 => x = 10.\nFather's present age y = 5(10) - 8 = 42 years.",
    shortcut: "Substitute options for Father. 42 => son 2 years ago was (40/5) = 8 => son present = 10. Check future: 44 = 3(12) + 8 = 44. Matches!",
    company: "Deloitte"
  },
  {
    id: 5024,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Past Ratios",
    q: "The ratio of the present ages of Suresh and Ramesh is 3:4. Five years ago, the ratio of their ages was 5:7. Find Suresh's present age.",
    options: ["A) 24 years", "B) 27 years", "C) 30 years", "D) 33 years"],
    answer: "C) 30 years",
    explanation: "Let present ages be 3x and 4x.\nFive years ago: (3x - 5)/(4x - 5) = 5/7\n7(3x - 5) = 5(4x - 5) => 21x - 35 = 20x - 25 => x = 10.\nSuresh's present age = 3x = 3(10) = 30 years.",
    shortcut: "Test options: Suresh = 30 => Ramesh = 40. 5 years ago: 25:35 = 5:7. Matches!",
    company: "TCS Ninja"
  },
  {
    id: 5025,
    topic: "problems-ages",
    difficulty: "medium",
    category: "Multi-person Relations",
    q: "A is elder to B by 6 years. A's father F is thrice as old as A, and B is twice as old as his sister S. If the ages of F and S differ by 48 years, find A's present age.",
    options: ["A) 16 years", "B) 18 years", "C) 20 years", "D) 22 years"],
    answer: "B) 18 years",
    explanation: "Let B's age be x. A's age = x + 6. Father F = 3(x + 6) = 3x + 18.\nSince B is twice S, S = x/2.\nGiven F - S = 48 => (3x + 18) - x/2 = 48 => 2.5x = 30 => x = 12.\nA's present age = x + 6 = 12 + 6 = 18 years.",
    shortcut: "Test options. If A = 18 => B = 12, F = 54, S = 6. F - S = 54 - 6 = 48. Matches!",
    company: "Infosys"
  },

  // === HARD (Q26-Q40) ===
  {
    id: 5026,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Birth Statement",
    q: "A father said to his son, \"I was as old as you are at present, at the time of your birth.\" If the father's age is 38 now, what was the son's age 5 years back?",
    options: ["A) 14 years", "B) 19 years", "C) 33 years", "D) 38 years"],
    answer: "A) 14 years",
    explanation: "Let son's present age be x.\nAt son's birth, father's age = 38 - x.\nGiven: 38 - x = x => 2x = 38 => x = 19.\nSon's age 5 years back = 19 - 5 = 14 years.",
    shortcut: "\"I was as old as you are now at your birth\" implies Father is twice son's age. Son = 38/2 = 19. 5 yrs ago = 14.",
    company: "Google, TCS Digital"
  },
  {
    id: 5027,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Comparative Timeline",
    q: "In 10 years, A will be twice as old as B was 10 years ago. If A is now 9 years older than B, what is the present age of B?",
    options: ["A) 19 years", "B) 29 years", "C) 39 years", "D) 49 years"],
    answer: "C) 39 years",
    explanation: "Let B's present age be x. A's present age = x + 9.\nIn 10 years: A's age = x + 9 + 10 = x + 19.\nB's age 10 years ago = x - 10.\nEquation: x + 19 = 2(x - 10) => x + 19 = 2x - 20 => x = 39.\nB's present age is 39 years.",
    shortcut: "x + 19 = 2x - 20 => x = 39.",
    company: "Amazon"
  },
  {
    id: 5028,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Difference and Past Multiple",
    q: "Rahul is 15 years older than Rohan. Five years ago, Rahul's age was three times Rohan's age at that time. What is Rahul's present age?",
    options: ["A) 22.5 years", "B) 27.5 years", "C) 25 years", "D) 24.9 years"],
    answer: "B) 27.5 years",
    explanation: "Let Rohan's age be y. Rahul's age = y + 15.\nFive years ago: Rahul = y + 10, Rohan = y - 5.\nEquation: y + 10 = 3(y - 5) => y + 10 = 3y - 15 => 2y = 25 => y = 12.5.\nRahul's present age = 12.5 + 15 = 27.5 years.",
    shortcut: "Difference is always 15. At 3:1 ratio, the difference of 2 parts = 15 => Rohan was 7.5. Rahul present = (7.5 * 3) + 5 = 27.5.",
    company: "Accenture"
  },
  {
    id: 5029,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Multi-person Sum Ratios",
    q: "The sum of the present ages of a father and his two sons is 115 years. Ten years ago, the sum of the ages of the two sons was 25 years, and the father's age was four times the elder son's age. What was the father's age 10 years ago?",
    options: ["A) 40 years", "B) 50 years", "C) 60 years", "D) 70 years"],
    answer: "C) 60 years",
    explanation: "Let the ages of the two sons 10 years ago be e (elder) and y (younger).\ne + y = 25 => y = 25 - e.\nFather's age 10 years ago = 4e.\nPresent ages: Elder = e + 10, Younger = 25 - e + 10 = 35 - e, Father = 4e + 10.\nSum of present ages = (4e + 10) + (e + 10) + (35 - e) = 115\n4e + 55 = 115 => 4e = 60 => e = 15.\nFather's age 10 years ago = 4e = 4(15) = 60 years.",
    shortcut: "Present sum of sons = 25 + 20 = 45. Present Father = 115 - 45 = 70. Father 10 yrs ago = 60.",
    company: "Goldman Sachs"
  },
  {
    id: 5030,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Double Ratio Shift",
    q: "The ratio of ages of A and B, five years ago, was 3:4. The ratio of their ages six years hence will be 4:5. What is the sum of their present ages?",
    options: ["A) 77 years", "B) 82 years", "C) 87 years", "D) 92 years"],
    answer: "C) 87 years",
    explanation: "Let ages 5 years ago be 3x and 4x. Present ages: 3x + 5 and 4x + 5.\nSix years hence: A = 3x + 11, B = 4x + 11.\nEquation: (3x + 11)/(4x + 11) = 4/5\n5(3x + 11) = 4(4x + 11) => 15x + 55 = 16x + 44 => x = 11.\nPresent ages: A = 3(11) + 5 = 38, B = 4(11) + 5 = 49.\nSum = 38 + 49 = 87 years.",
    shortcut: "Both parts in ratio increase by 1 (3 to 4, and 4 to 5). Total gap = 5 + 6 = 11 years. So 1 part = 11. Sum 5 years ago = 7 parts = 77. Present sum = 77 + 10 = 87.",
    company: "TCS Digital"
  },
  {
    id: 5031,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Long-term Multiples",
    q: "Twenty years ago, the age of a father was eight times the age of his son. Now the father's age is thrice the age of his son. Find the present age of the son.",
    options: ["A) 24 years", "B) 26 years", "C) 28 years", "D) 30 years"],
    answer: "C) 28 years",
    explanation: "Let son's present age be x. Father's present age = 3x.\nTwenty years ago: Father = 3x - 20, Son = x - 20.\nEquation: 3x - 20 = 8(x - 20) => 3x - 20 = 8x - 160 => 5x = 140 => x = 28.\nSon's present age is 28 years.",
    shortcut: "3x - 20 = 8x - 160 => 5x = 140 => x = 28.",
    company: "Deloitte"
  },
  {
    id: 5032,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Average Age and Births",
    q: "The average age of a family of 5 members is 24 years. If the age of the youngest member is 8 years, what was the average age of the family at the time of birth of the youngest member?",
    options: ["A) 18 years", "B) 20 years", "C) 22 years", "D) 24 years"],
    answer: "B) 20 years",
    explanation: "Total present age of 5 members = 5 * 24 = 120 years.\nAt the birth of the youngest (8 years ago), we subtract 8 years from all 5 members.\nTotal age then = 120 - (5 * 8) = 80 years.\nAt that time, the youngest was just born (age 0), so we count the other 4 members.\nAverage age of the 4 members = 80 / 4 = 20 years.",
    shortcut: "Total sum 8 years ago = 120 - 40 = 80. Divide by 4 members = 20.",
    company: "Infosys"
  },
  {
    id: 5033,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Average Overlaps",
    q: "The average age of a husband, wife, and their child 3 years ago was 27 years, and that of the wife and child 5 years ago was 20 years. What is the present age of the husband?",
    options: ["A) 35 years", "B) 38 years", "C) 40 years", "D) 42 years"],
    answer: "C) 40 years",
    explanation: "Sum of ages of H, W, and C 3 years ago = 3 * 27 = 81 years.\nPresent sum of H, W, and C = 81 + (3 * 3) = 90 years.\nSum of ages of W and C 5 years ago = 2 * 20 = 40 years.\nPresent sum of W and C = 40 + (2 * 5) = 50 years.\nHusband's present age = Present sum of all - Present sum of W & C = 90 - 50 = 40 years.",
    shortcut: "Present total = 81 + 9 = 90. Present W+C = 40 + 10 = 50. H = 90 - 50 = 40.",
    company: "Capgemini"
  },
  {
    id: 5034,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Three-person Ratio Sum",
    q: "The present ages of A, B, and C are in the ratio 3:4:5. Eight years ago, the sum of their ages was 48 years. Find the present age of C.",
    options: ["A) 24 years", "B) 27 years", "C) 30 years", "D) 33 years"],
    answer: "C) 30 years",
    explanation: "Let present ages be 3x, 4x, and 5x. Sum of present ages = 12x.\nEight years ago sum was 48: 12x - 3(8) = 48 => 12x - 24 = 48 => 12x = 72 => x = 6.\nC's present age = 5x = 5(6) = 30 years.",
    shortcut: "Present sum = 48 + 24 = 72. 12 parts = 72 => 1 part = 6. C = 5 parts = 30.",
    company: "Wipro"
  },
  {
    id: 5035,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Double Ratio Shift",
    q: "Ten years ago, the ages of A and B were in the ratio 1:3. Fifteen years from now, the ratio of their ages will be 7:11. Find A's present age.",
    options: ["A) 15 years", "B) 18 years", "C) 20 years", "D) 22 years"],
    answer: "C) 20 years",
    explanation: "Let ages 10 years ago be x and 3x. Present ages: x + 10 and 3x + 10.\nFifteen years hence: A = x + 25, B = 3x + 25.\nEquation: (x + 25)/(3x + 25) = 7/11\n11(x + 25) = 7(3x + 25) => 11x + 275 = 21x + 175 => 10x = 100 => x = 10.\nA's present age = x + 10 = 10 + 10 = 20 years.",
    shortcut: "Test options: If A = 20 => B = 40 (since 10 yrs ago A was 10, so B was 30 => B present is 40). In 15 years: A = 35, B = 55. 35:55 = 7:11. Matches!",
    company: "Goldman Sachs"
  },
  {
    id: 5036,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Multiple Difference",
    q: "A grandfather is 10 times older than his granddaughter. He is also 54 years older than her. What will be the grandfather's age after 8 years?",
    options: ["A) 62 years", "B) 65 years", "C) 68 years", "D) 70 years"],
    answer: "C) 68 years",
    explanation: "Let the granddaughter's age be x. Grandfather's age = 10x.\nGiven: 10x - x = 54 => 9x = 54 => x = 6.\nGrandfather's present age = 10(6) = 60 years.\nAge after 8 years = 60 + 8 = 68 years.",
    shortcut: "9 parts = 54 => 1 part = 6. Grandfather = 60. After 8 years = 68.",
    company: "TCS Digital"
  },
  {
    id: 5037,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Three-person Ratio Sum",
    q: "The present ages of three brothers are in the ratio 2:3:4. Five years hence, the sum of their ages will be 60 years. Find the present age of the youngest brother.",
    options: ["A) 8 years", "B) 10 years", "C) 12 years", "D) 14 years"],
    answer: "B) 10 years",
    explanation: "Let present ages be 2x, 3x, and 4x.\nFive years hence, sum of ages = 9x + 15 = 60 => 9x = 45 => x = 5.\nYoungest brother's present age = 2x = 2(5) = 10 years.",
    shortcut: "Present sum = 60 - 15 = 45. 9 parts = 45 => 1 part = 5. Youngest = 2 * 5 = 10.",
    company: "Accenture"
  },
  {
    id: 5038,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Past Multiples",
    q: "A is twice as old as B. Ten years ago, A was thrice as old as B. Find B's present age.",
    options: ["A) 15 years", "B) 18 years", "C) 20 years", "D) 24 years"],
    answer: "C) 20 years",
    explanation: "Let B's present age be x. A's present age = 2x.\nTen years ago: A was 2x - 10, B was x - 10.\nEquation: 2x - 10 = 3(x - 10) => 2x - 10 = 3x - 30 => x = 20.\nB's present age is 20 years.",
    shortcut: "2x - 10 = 3x - 30 => x = 20.",
    company: "Amazon"
  },
  {
    id: 5039,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Product Condition",
    q: "The ratio of a father's age to his son's age is 4:1. The product of their ages is 196. What will be the ratio of their ages after 5 years?",
    options: ["A) 11:4", "B) 3:1", "C) 5:2", "D) 9:4"],
    answer: "A) 11:4",
    explanation: "Let ages be 4x and x.\nProduct = 4x * x = 4x² = 196 => x² = 49 => x = 7.\nFather = 28 years, Son = 7 years.\nAfter 5 years: Father = 33, Son = 12.\nRatio = 33 : 12 = 11 : 4.",
    shortcut: "4x² = 196 => x = 7. Present: 28 and 7. Add 5: 33 and 12 => 11:4.",
    company: "Google"
  },
  {
    id: 5040,
    topic: "problems-ages",
    difficulty: "hard",
    category: "Simultaneous Equations",
    q: "Rahul's father was 4 times as old as Rahul 8 years ago. After 8 years, the father will be twice as old as Rahul. Find Rahul's present age.",
    options: ["A) 12 years", "B) 14 years", "C) 16 years", "D) 18 years"],
    answer: "C) 16 years",
    explanation: "Let Rahul's present age be x. Father's present age be y.\n8 years ago: y - 8 = 4(x - 8) => y = 4x - 24  (Eqn 1)\nAfter 8 years: y + 8 = 2(x + 8) => y = 2x + 8 (Eqn 2)\nEquating Eqns: 4x - 24 = 2x + 8 => 2x = 32 => x = 16.\nRahul's present age is 16 years.",
    shortcut: "Test options. 16 => Father was 4(8) + 8 = 40. In 8 years: Rahul is 24, Father is 48. Twice as old. Matches!",
    company: "TCS Ninja"
  }
];
